import type { P4PFighter } from "./P4PChampions";

const P4PChampionsArray: P4PFighter[] = [
    {
        p4pRank: 1,
        name: 'Ислам Махачев',
        nickname: null,
        weightClass: 'Полусредний вес',
        record: '28-1-0',
    },
    {
        p4pRank: 2,
        name: 'Илия Топурия',
        nickname: `«La Leyenda»`,
        weightClass: 'Лёгкий вес',
        record: '17-0-0',
    },
    {
        p4pRank: 3,
        name: 'Александр Волкановски',
        nickname: `«The Great»`,
        weightClass: 'Полулегкий вес',
        record: '28-4-0',
    },
    {
        p4pRank: 4,
        name: 'Алекс Перейра',
        nickname: `«Poatan»`,
        weightClass: 'Тяжёлый вес',
        record: '13-3-0',
    },
    {
        p4pRank: 5,
        name: 'Пётр Ян',
        nickname: `«No Mercy»`,
        weightClass: 'Легчайший вес',
        record: '20-5-0',
    },
    {
        p4pRank: 6,
        name: 'Том Аспинэлл',
        nickname: null,
        weightClass: 'Тяжелый вес',
        record: '15-3-0',
    },
    {
        p4pRank: 7,
        name: 'Шон Стрикланд',
        nickname: `«Tarzan»`,
        weightClass: 'Средний вес',
        record: '31-7-0',
    },
    {
        p4pRank: 8,
        name: 'Мераб Двалишвили',
        nickname: `«The Machine»`,
        weightClass: 'Легчайший вес',
        record: '21-5-0',
    },
    {
        p4pRank: 9,
        name: 'Джошуа Ван',
        nickname: `«The Fearless»`,
        weightClass: 'Наилегчайший вес',
        record: '17-2-0',
    },
    {
        p4pRank: 10,
        name: 'Хамзат Чимаев',
        nickname: `«Borz»`,
        weightClass: 'Средний вес',
        record: '15-1-0',
    },
    {
        p4pRank: 11,
        name: 'Александр Пантожа',
        nickname: `«The Cannibal»`,
        weightClass: 'Наилегчайший вес',
        record: '30-6-0',
    },
    {
        p4pRank: 12,
        name: 'Чарльз Оливейра',
        nickname: `«Do Bronx»`,
        weightClass: 'Легкий вес',
        record: '37-11-0',
    },
    {
        p4pRank: 13,
        name: 'Дрикус Дю Плесси',
        nickname: `«Stillknocks»`,
        weightClass: 'Средний вес',
        record: '23-3-0',
    },
    {
        p4pRank: 14,
        name: 'Карлос Олберг',
        nickname: `«Black Jag»`,
        weightClass: 'Полутяжелый вес',
        record: '15-1-0',
    },
    {
        p4pRank: 15,
        name: 'Арман Царукян',
        nickname: `«Tough Guy»`,
        weightClass: 'Легкий вес',
        record: '23-3-0',
    },
];

export default P4PChampionsArray;