import type { P4PFighter } from "./P4PChampions";

const P4PChampionsArray: P4PFighter[] = [
  {
    p4pRank: 1,
    name: "Islam Makhachev",
    nickname: null,
    weightClass: "welterweight",
    record: "28-1-0",
  },
  {
    p4pRank: 2,
    name: "Ilia Topuria",
    nickname: "La Leyenda",
    weightClass: "lightweight",
    record: "17-0-0",
  },
  {
    p4pRank: 3,
    name: "Alexander Volkanovski",
    nickname: "The Great",
    weightClass: "featherweight",
    record: "28-4-0",
  },
  {
    p4pRank: 4,
    name: "Alex Pereira",
    nickname: "Poatan",
    weightClass: "heavyweight",
    record: "13-3-0",
  },
  {
    p4pRank: 5,
    name: "Petr Yan",
    nickname: "No Mercy",
    weightClass: "bantamweight",
    record: "20-5-0",
  },
  {
    p4pRank: 6,
    name: "Tom Aspinall",
    nickname: null,
    weightClass: "heavyweight",
    record: "15-3-0",
  },
  {
    p4pRank: 7,
    name: "Sean Strickland",
    nickname: "Tarzan",
    weightClass: "middleweight",
    record: "31-7-0",
  },
  {
    p4pRank: 8,
    name: "Merab Dvalishvili",
    nickname: "The Machine",
    weightClass: "bantamweight",
    record: "21-5-0",
  },
  {
    p4pRank: 9,
    name: "Joshua Van",
    nickname: "The Fearless",
    weightClass: "flyweight",
    record: "17-2-0",
  },
  {
    p4pRank: 10,
    name: "Khamzat Chimaev",
    nickname: "Borz",
    weightClass: "middleweight",
    record: "15-1-0",
  },
  {
    p4pRank: 11,
    name: "Alexandre Pantoja",
    nickname: "The Cannibal",
    weightClass: "flyweight",
    record: "30-6-0",
  },
  {
    p4pRank: 12,
    name: "Charles Oliveira",
    nickname: "Do Bronx",
    weightClass: "lightweight",
    record: "37-11-0",
  },
  {
    p4pRank: 13,
    name: "Dricus du Plessis",
    nickname: "Stillknocks",
    weightClass: "middleweight",
    record: "23-3-0",
  },
  {
    p4pRank: 14,
    name: "Carlos Ulberg",
    nickname: "Black Jag",
    weightClass: "lightHeavyweight",
    record: "15-1-0",
  },
  {
    p4pRank: 15,
    name: "Arman Tsarukyan",
    nickname: "Tough Guy",
    weightClass: "lightweight",
    record: "23-3-0",
  },
];

export default P4PChampionsArray;