import type { fighterType } from "../Fighters.types";
import PeterYan from "../../../../../public/PeterYan.png";
import MerabDvalishvili from "../../../../../public/MerabDvalishvili.png";
import UmarNurmagomedov from "../../../../../public/UmarNurmagomedov.png";
import SeanOMalley from "../../../../../public/SeanOMalley.png";
import SongYadong from "../../../../../public/SongYadong.png";
import CoreySandhagen from "../../../../../public/CoreySandhagen.png";
import MarioBautista from "../../../../../public/MarioBautista.png";
import AimannZahabi from "../../../../../public/AimannZahabi.png";
import DavesonFigueredo from "../../../../../public/DavesonFigueredo.png";
import DavidMartinez from "../../../../../public/DavidMartinez.png";
import MarlonVera from "../../../../../public/MarlonVera.png";
import ViniciusOliveira from "../../../../../public/ViniciusOliveira.png";
import PaytonTalbott from "../../../../../public/PaytonTalbott.png";
import RaulRosasJr from "../../../../../public/RaulRosasJr.png";
import MontelJackson from "../../../../../public/MontelJackson.png";
import FaridBasharat from "../../../../../public/FaridBasharat.png";

export const bantaWeight: fighterType[] = [
    {
        name: 'Пётр Ян',
        nickname: `"No Mercy"`,
        rang: 0,
        victory: 20,
        defeat: 5,
        draw: 0,
        country: 'Россия',
        isChampion: true,
        KO: 7,
        DES: 12,
        SUB: 1,
        img: `${PeterYan}`,
        age: 33,
        height: 171.45,
        weight: 61.23,
        debut: '23.06.18',
        armSpan: 170.18,
    },
    {
        name: 'Мераб Двалишвили ',
        nickname: null,
        rang: 1,
        victory: 21,
        defeat: 5,
        draw: 0,
        country: 'Грузия',
        isChampion: false,
        KO: 3,
        DES: 16,
        SUB: 2,
        img: `${MerabDvalishvili}`,
        age: 35,
        height: 167.64,
        weight: 61.23,
        debut: '09.12.17',
        armSpan: 172.72,
    },
    {
        name: 'Умар Нурмагомедов',
        nickname: null,
        rang: 2,
        victory: 20,
        defeat: 1,
        draw: 0,
        country: 'Россия',
        isChampion: false,
        KO: 2,
        DES: 11,
        SUB: 7,
        img: `${UmarNurmagomedov}`,
        age: 30,
        height: 172.72,
        weight: 61.69,
        debut: '20.01.21',
        armSpan: 175.26,
    },
    {
        name: `Шон О'Мэлли`,
        nickname: `"Sugar"`,
        rang: 3,
        victory: 19,
        defeat: 3,
        draw: 0,
        country: 'США',
        isChampion: false,
        KO: 12,
        DES: 6,
        SUB: 1,
        img: `${SeanOMalley}`,
        age: 31,
        height: 180.34,
        weight: 61.46,
        debut: '18.07.17',
        armSpan: 182.88,
    },
    {
        name: 'Кори Сэндхаген',
        nickname: null,
        rang: 4,
        victory: 18,
        defeat: 6,
        draw: 0,
        country: 'США',
        isChampion: false,
        KO: 8,
        DES: 7,
        SUB: 3,
        img: `${CoreySandhagen}`,
        age: 33,
        height: 180.34,
        weight: 61.01,
        debut: '28.01.18',
        armSpan: 177.8,
    },
    {
        name: 'Сонг Ядонг',
        nickname: null,
        rang: 5,
        victory: 22,
        defeat: 9,
        draw: 1,
        country: 'Китай',
        isChampion: false,
        KO: 9,
        DES: 10,
        SUB: 3,
        img: `${SongYadong}`,
        age: 28,
        height: 172.72,
        weight: 61.69,
        debut: '25.11.17',
        armSpan: 170.18,
    },
    {
        name: 'Айманн Захаби',
        nickname: null,
        rang: 6,
        victory: 14,
        defeat: 2,
        draw: 0,
        country: 'Канада',
        isChampion: false,
        KO: 6,
        DES: 6,
        SUB: 2,
        img: `${AimannZahabi}`,
        age: 38,
        height: 172.72,
        weight: 61.46,
        debut: '20.02.17',
        armSpan: 173.99,
    },
    {
        name: 'Дейвесон Фигередо',
        nickname: `"Deus da Guerra"`,
        rang: 7,
        victory: 25,
        defeat: 6,
        draw: 1,
        country: 'Бразилия',
        isChampion: false,
        KO: 9,
        DES: 7,
        SUB: 9,
        img: `${DavesonFigueredo}`,
        age: 38,
        height: 165.1,
        weight: 62.82,
        debut: '03.06.17',
        armSpan: 172.72,
    },
    {
        name: 'Марио Баутиста',
        nickname: null,
        rang: 8,
        victory: 17,
        defeat: 3,
        draw: 0,
        country: 'США',
        isChampion: false,
        KO: 9,
        DES: 7,
        SUB: 9,
        img: `${MarioBautista}`,
        age: 32,
        height: 175.26,
        weight: 61.46,
        debut: '19.01.19',
        armSpan: 182.88,
    },
    {
        name: 'Дэвид Мартинез',
        nickname: null,
        rang: 9,
        victory: 14,
        defeat: 1,
        draw: 0,
        country: 'Мексика',
        isChampion: false,
        KO: 10,
        DES: 4,
        SUB: 0,
        img: `${DavidMartinez}`,
        age: 27,
        height: 165.1,
        weight: 61.46,
        debut: '29.03.25',
        armSpan: 171.45,
    },
    {
        name: 'Марлон Вера',
        nickname: `"Chito"`,
        rang: 10,
        victory: 23,
        defeat: 12,
        draw: 1,
        country: 'Эквадор',
        isChampion: false,
        KO: 8,
        DES: 5,
        SUB: 10,
        img: `${MarlonVera}`,
        age: 33,
        height: 172.72,
        weight: 61.69,
        debut: '15.11.14',
        armSpan: 179.07,
    },
    {
        name: 'Пэйтон Тэлботт',
        nickname: null,
        rang: 11,
        victory: 11,
        defeat: 1,
        draw: 0,
        country: 'США',
        isChampion: false,
        KO: 7,
        DES: 3,
        SUB: 1,
        img: `${PaytonTalbott}`,
        age: 27,
        height: 177.8,
        weight: 61.69,
        debut: '18.11.23',
        armSpan: 179.07,
    },
    {
        name: 'Винисиус Оливейрат',
        nickname: null,
        rang: 12,
        victory: 23,
        defeat: 4,
        draw: 0,
        country: 'Бразилия',
        isChampion: false,
        KO: 16,
        DES: 5,
        SUB: 2,
        img: `${ViniciusOliveira}`,
        age: 30,
        height: 175.26,
        weight: 61.69,
        debut: '02.03.24',
        armSpan: 179.07,
    },
    {
        name: 'Рауль Росас мл.',
        nickname: null,
        rang: 13,
        victory: 13,
        defeat: 1,
        draw: 0,
        country: 'Бразилия',
        isChampion: false,
        KO: 2,
        DES: 4,
        SUB: 6,
        img: `${RaulRosasJr}`,
        age: 21,
        height: 175.26,
        weight: 61.23,
        debut: '10.12.22',
        armSpan: 170.18,
    },
    {
        name: 'Монтел Джексон',
        nickname: `"Quik"`,
        rang: 14,
        victory: 15,
        defeat: 3,
        draw: 0,
        country: 'США',
        isChampion: false,
        KO: 2,
        DES: 4,
        SUB: 6,
        img: `${MontelJackson}`,
        age: 33,
        height: 177.8,
        weight: 61.69,
        debut: '04.08.18',
        armSpan: 191.77,
    },
    {
        name: 'Фарид Башарат',
        nickname: null,
        rang: 15,
        victory: 15,
        defeat: 0,
        draw: 0,
        country: 'Афганистан',
        isChampion: false,
        KO: 2,
        DES: 4,
        SUB: 6,
        img: `${FaridBasharat}`,
        age: 28,
        height: 172.72,
        weight: 61.69,
        debut: '04.03.23',
        armSpan: 180.34,
    },
];