import type { fighterType } from "../Fighters.types";

export const bantaWeight: fighterType[] = [
    {
        name: "Petr Yan",
        nickname: "No Mercy",
        rang: 0,
        victory: 20,
        defeat: 5,
        draw: 0,
        country: "RU",
        isChampion: true,
        KO: 7,
        DES: 12,
        SUB: 1,
        img: "/PeterYan.webp",
        age: 33,
        height: 171,
        weight: 61.2,
        debut: "23.06.18",
        armSpan: 170,
    },
    {
        name: "Merab Dvalishvili",
        nickname: "The Machine",
        rang: 1,
        victory: 21,
        defeat: 5,
        draw: 0,
        country: "GE",
        isChampion: false,
        KO: 3,
        DES: 16,
        SUB: 2,
        img: "/MerabDvalishvili.webp",
        age: 35,
        height: 168,
        weight: 61.2,
        debut: "09.12.17",
        armSpan: 173,
    },
    {
        name: "Umar Nurmagomedov",
        nickname: "The Young Eagle",
        rang: 2,
        victory: 20,
        defeat: 1,
        draw: 0,
        country: "RU",
        isChampion: false,
        KO: 2,
        DES: 11,
        SUB: 7,
        img: "/UmarNurmagomedov.webp",
        age: 30,
        height: 173,
        weight: 61.2,
        debut: "20.01.21",
        armSpan: 175,
    },
    {
        name: "Sean O'Malley",
        nickname: "Sugar",
        rang: 3,
        victory: 19,
        defeat: 3,
        draw: 0,
        country: "US",
        isChampion: false,
        KO: 12,
        DES: 6,
        SUB: 1,
        img: "/SeanOMalley.webp",
        age: 31,
        height: 180,
        weight: 61.2,
        debut: "18.07.17",
        armSpan: 183,
    },
    {
        name: "Cory Sandhagen",
        nickname: "The Sandman",
        rang: 4,
        victory: 18,
        defeat: 6,
        draw: 0,
        country: "US",
        isChampion: false,
        KO: 8,
        DES: 7,
        SUB: 3,
        img: "/CoreySandhagen.webp",
        age: 33,
        height: 180,
        weight: 61.2,
        debut: "28.01.18",
        armSpan: 178,
    },
    {
        name: "Song Yadong",
        nickname: "The Kung Fu Kid",
        rang: 5,
        victory: 22,
        defeat: 9,
        draw: 1,
        country: "CN",
        isChampion: false,
        KO: 9,
        DES: 10,
        SUB: 3,
        img: "/SongYadong.webp",
        age: 28,
        height: 173,
        weight: 61.2,
        debut: "25.11.17",
        armSpan: 170,
    },
    {
        name: "Aiemann Zahabi",
        nickname: null,
        rang: 6,
        victory: 14,
        defeat: 2,
        draw: 0,
        country: "CA",
        isChampion: false,
        KO: 6,
        DES: 6,
        SUB: 2,
        img: "/AimannZahabi.webp",
        age: 38,
        height: 173,
        weight: 61.2,
        debut: "20.02.17",
        armSpan: 174,
    },
    {
        name: "Deiveson Figueiredo",
        nickname: "Deus da Guerra",
        rang: 7,
        victory: 25,
        defeat: 6,
        draw: 1,
        country: "BR",
        isChampion: false,
        KO: 9,
        DES: 7,
        SUB: 9,
        img: "/DavesonFigueredo.webp",
        age: 38,
        height: 165,
        weight: 61.2,
        debut: "03.06.17",
        armSpan: 173,
    },
    {
        name: "Mario Bautista",
        nickname: null,
        rang: 8,
        victory: 17,
        defeat: 3,
        draw: 0,
        country: "US",
        isChampion: false,
        KO: 3,
        DES: 7,
        SUB: 7,
        img: "/MarioBautista.webp",
        age: 32,
        height: 175,
        weight: 61.2,
        debut: "19.01.19",
        armSpan: 183,
    },
    {
        name: "David Martinez",
        nickname: "Black Spartan",
        rang: 9,
        victory: 14,
        defeat: 1,
        draw: 0,
        country: "MX",
        isChampion: false,
        KO: 10,
        DES: 4,
        SUB: 0,
        img: "/DavidMartinez.webp",
        age: 27,
        height: 165,
        weight: 61.2,
        debut: "29.03.25",
        armSpan: 171,
    },
    {
        name: "Marlon Vera",
        nickname: "Chito",
        rang: 10,
        victory: 23,
        defeat: 12,
        draw: 1,
        country: "EC",
        isChampion: false,
        KO: 8,
        DES: 5,
        SUB: 10,
        img: "/MarlonVera.webp",
        age: 33,
        height: 173,
        weight: 61.2,
        debut: "15.11.14",
        armSpan: 179,
    },
    {
        name: "Payton Talbott",
        nickname: null,
        rang: 11,
        victory: 11,
        defeat: 1,
        draw: 0,
        country: "US",
        isChampion: false,
        KO: 7,
        DES: 3,
        SUB: 1,
        img: "/PaytonTalbott.webp",
        age: 27,
        height: 178,
        weight: 61.2,
        debut: "18.11.23",
        armSpan: 179,
    },
    {
        name: "Vinicius Oliveira",
        nickname: "Lok Dog",
        rang: 12,
        victory: 23,
        defeat: 4,
        draw: 0,
        country: "BR",
        isChampion: false,
        KO: 16,
        DES: 5,
        SUB: 2,
        img: "/ViniciusOliveira.webp",
        age: 30,
        height: 175,
        weight: 61.2,
        debut: "02.03.24",
        armSpan: 179,
    },
    {
        name: "Raul Rosas Jr.",
        nickname: "El Niño Problema",
        rang: 13,
        victory: 13,
        defeat: 1,
        draw: 0,
        country: "US",
        isChampion: false,
        KO: 2,
        DES: 4,
        SUB: 7,
        img: "/RaulRosasJr.webp",
        age: 21,
        height: 175,
        weight: 61.2,
        debut: "10.12.22",
        armSpan: 170,
    },
    {
        name: "Montel Jackson",
        nickname: "Quik",
        rang: 14,
        victory: 15,
        defeat: 4,
        draw: 0,
        country: "US",
        isChampion: false,
        KO: 8,
        DES: 6,
        SUB: 1,
        img: "/MontelJackson.webp",
        age: 33,
        height: 178,
        weight: 61.2,
        debut: "04.08.18",
        armSpan: 192,
    },
    {
        name: "Farid Basharat",
        nickname: "Ferocious",
        rang: 15,
        victory: 15,
        defeat: 0,
        draw: 0,
        country: "AF",
        isChampion: false,
        KO: 1,
        DES: 8,
        SUB: 6,
        img: "/FaridBasharat.webp",
        age: 28,
        height: 173,
        weight: 61.2,
        debut: "04.03.23",
        armSpan: 180,
    },
];