import type { fighterType } from "../Fighters.types";
import AlexanderVolkanovsky from "../../../../../public/AlexanderVolkanovsky.png";
import MovsarYevloyev from "../../../../../public/MovsarYevloyev.png";
import DiegoLopez from "../../../../../public/DiegoLopez.png";
import LeronMurphy from "../../../../../public/LeronMurphy.png";
import YairRodriguez from "../../../../../public/YairRodriguez.png";
import AlgemaineSterling from "../../../../../public/AlgemaineSterling.png";
import JeanSilva from "../../../../../public/JeanSilva.png";
import YoussefZalal from "../../../../../public/YoussefZalal.png";
import ArnoldAllen from "../../../../../public/ArnoldAllen.png";
import SteveGarcia from "../../../../../public/SteveGarcia.png";
import KevinVallejos from "../../../../../public/KevinVallejos.png";
import BrianOrtega from "../../../../../public/BrianOrtega.png";
import MelkizaelCosta from "../../../../../public/MelkizaelCosta.png";
import AaronPico from "../../../../../public/AaronPico.png";
import DavidOnama from "../../../../../public/DavidOnama.png";
import PatricioPitbull from "../../../../../public/PatricioPitbull.png";

export const featherWeight: fighterType[] = [
  {
    name: "Alexander Volkanovski",
    nickname: "The Great",
    rang: 0,
    victory: 28,
    defeat: 4,
    draw: 0,
    country: "AU",
    isChampion: true,
    KO: 13,
    DES: 12,
    SUB: 3,
    img: `${AlexanderVolkanovsky}`,
    age: 37,
    height: 168,
    weight: 65.8,
    debut: "15.10.16",
    armSpan: 182,
  },
  {
    name: "Movsar Evloev",
    nickname: "Fearless",
    rang: 1,
    victory: 20,
    defeat: 0,
    draw: 0,
    country: "RU",
    isChampion: false,
    KO: 3,
    DES: 13,
    SUB: 4,
    img: `${MovsarYevloyev}`,
    age: 32,
    height: 170,
    weight: 65.8,
    debut: "20.04.19",
    armSpan: 184,
  },
  {
    name: "Diego Lopes",
    nickname: null,
    rang: 2,
    victory: 27,
    defeat: 8,
    draw: 0,
    country: "BR",
    isChampion: false,
    KO: 11,
    DES: 4,
    SUB: 12,
    img: `${DiegoLopez}`,
    age: 31,
    height: 180,
    weight: 65.8,
    debut: "06.05.23",
    armSpan: 184,
  },
  {
    name: "Lerone Murphy",
    nickname: "The Miracle",
    rang: 3,
    victory: 17,
    defeat: 1,
    draw: 1,
    country: "GB",
    isChampion: false,
    KO: 8,
    DES: 9,
    SUB: 0,
    img: `${LeronMurphy}`,
    age: 34,
    height: 175,
    weight: 65.8,
    debut: "07.09.19",
    armSpan: 187,
  },
  {
    name: "Aljamain Sterling",
    nickname: "Funk Master",
    rang: 4,
    victory: 25,
    defeat: 5,
    draw: 0,
    country: "US",
    isChampion: false,
    KO: 3,
    DES: 14,
    SUB: 8,
    img: `${AlgemaineSterling}`,
    age: 36,
    height: 170,
    weight: 65.8,
    debut: "22.02.14",
    armSpan: 180,
  },
  {
    name: "Yair Rodriguez",
    nickname: "El Pantera",
    rang: 5,
    victory: 21,
    defeat: 5,
    draw: 0,
    country: "MX",
    isChampion: false,
    KO: 8,
    DES: 8,
    SUB: 5,
    img: `${YairRodriguez}`,
    age: 33,
    height: 180,
    weight: 65.8,
    debut: "15.11.14",
    armSpan: 180,
  },
  {
    name: "Jean Silva",
    nickname: "Lord",
    rang: 6,
    victory: 17,
    defeat: 3,
    draw: 0,
    country: "BR",
    isChampion: false,
    KO: 12,
    DES: 2,
    SUB: 3,
    img: `${JeanSilva}`,
    age: 29,
    height: 170,
    weight: 65.8,
    debut: "13.01.24",
    armSpan: 175,
  },
  {
    name: "Arnold Allen",
    nickname: "Almighty",
    rang: 7,
    victory: 21,
    defeat: 4,
    draw: 0,
    country: "GB",
    isChampion: false,
    KO: 7,
    DES: 10,
    SUB: 4,
    img: `${ArnoldAllen}`,
    age: 32,
    height: 173,
    weight: 65.8,
    debut: "20.06.15",
    armSpan: 178,
  },
  {
    name: "Youssef Zalal",
    nickname: "The Moroccan Devil",
    rang: 8,
    victory: 18,
    defeat: 5,
    draw: 1,
    country: "MA",
    isChampion: false,
    KO: 4,
    DES: 4,
    SUB: 10,
    img: `${YoussefZalal}`,
    age: 29,
    height: 178,
    weight: 65.8,
    debut: "08.02.20",
    armSpan: 183,
  },
  {
    name: "Steve Garcia",
    nickname: "Mean Machine",
    rang: 9,
    victory: 19,
    defeat: 5,
    draw: 0,
    country: "US",
    isChampion: false,
    KO: 15,
    DES: 4,
    SUB: 0,
    img: `${SteveGarcia}`,
    age: 33,
    height: 183,
    weight: 65.8,
    debut: "29.02.20",
    armSpan: 191,
  },
  {
    name: "Kevin Vallejos",
    nickname: "El Chino",
    rang: 10,
    victory: 18,
    defeat: 1,
    draw: 0,
    country: "AR",
    isChampion: false,
    KO: 13,
    DES: 3,
    SUB: 2,
    img: `${KevinVallejos}`,
    age: 24,
    height: 170,
    weight: 65.8,
    debut: "15.03.25",
    armSpan: 173,
  },
  {
    name: "Brian Ortega",
    nickname: "T-City",
    rang: 11,
    victory: 15,
    defeat: 5,
    draw: 0,
    country: "US",
    isChampion: false,
    KO: 3,
    DES: 4,
    SUB: 8,
    img: `${BrianOrtega}`,
    age: 35,
    height: 173,
    weight: 65.8,
    debut: "26.07.14",
    armSpan: 175,
  },
  {
    name: "Melquizael Costa",
    nickname: "Melk Cauthy",
    rang: 12,
    victory: 26,
    defeat: 8,
    draw: 0,
    country: "BR",
    isChampion: false,
    KO: 9,
    DES: 9,
    SUB: 8,
    img: `${MelkizaelCosta}`,
    age: 29,
    height: 178,
    weight: 65.8,
    debut: "21.01.23",
    armSpan: 180,
  },
  {
    name: "Aaron Pico",
    nickname: "Cheeks",
    rang: 13,
    victory: 14,
    defeat: 5,
    draw: 0,
    country: "US",
    isChampion: false,
    KO: 9,
    DES: 3,
    SUB: 2,
    img: `${AaronPico}`,
    age: 29,
    height: 173,
    weight: 65.8,
    debut: "26.07.25",
    armSpan: 179,
  },
  {
    name: "David Onama",
    nickname: "Silent Assassin",
    rang: 14,
    victory: 14,
    defeat: 3,
    draw: 0,
    country: "UG",
    isChampion: false,
    KO: 7,
    DES: 4,
    SUB: 3,
    img: `${DavidOnama}`,
    age: 31,
    height: 180,
    weight: 65.8,
    debut: "23.10.21",
    armSpan: 188,
  },
  {
    name: "Patricio Pitbull",
    nickname: "Pitbull",
    rang: 15,
    victory: 37,
    defeat: 9,
    draw: 0,
    country: "BR",
    isChampion: false,
    KO: 12,
    DES: 13,
    SUB: 12,
    img: `${PatricioPitbull}`,
    age: 38,
    height: 168,
    weight: 65.8,
    debut: "12.04.25",
    armSpan: 170,
  },
];