import type { fighterType } from "../Fighters.types";
import AlexanderVolkanovsky from "../../../../../public/AlexanderVolkanovsky.png";
import MovsarYevloyev from "../../../../../public/MovsarYevloyev.png";
import DiegoLopez from "../../../../../public/DiegoLopez.png";
import LeronMurphy from "../../../../../public/LeronMurphy.png";
import YairRodriguez from "../../../../../public/YairRodriguez.png";
import AlgemaineSterling from "../../../../../public/AlgemaineSterling.png";
import JeanSilva from "../../../../../public/JeanSilva.png";
import YoussefZalal from "../../../../../public/YoussefZalal.png";
import ArnoldAllen from "../../../../../public/ArnoldAllen.png";
import SteveGarcia from "../../../../../public/SteveGarcia.png";
import KevinVallejos from "../../../../../public/KevinVallejos.png";
import BrianOrtega from "../../../../../public/BrianOrtega.png";
import MelkizaelCosta from "../../../../../public/MelkizaelCosta.png";
import AaronPico from "../../../../../public/AaronPico.png";
import DavidOnama from "../../../../../public/DavidOnama.png";
import PatricioPitbull from "../../../../../public/PatricioPitbull.png";

export const featherWeight: fighterType[] = [
    {
        name: 'Александр Волкановски',
        nickname: `«The Great»`,
        rang: 0,
        victory: 28,
        defeat: 4,
        draw: 0,
        country: 'Австралия',
        isChampion: true,
        KO: 13,
        DES: 12,
        SUB: 3,
        img: `${AlexanderVolkanovsky}`,
        age: 37,
        height: 167.64,
        weight: 71.2,
        debut: '15.10.16',
        armSpan: 181.61,
    },
    {
        name: 'Мовсар Евлоев',
        nickname: `«Fearless»`,
        rang: 1,
        victory: 20,
        defeat: 0,
        draw: 0,
        country: 'Россия',
        isChampion: false,
        KO: 3,
        DES: 13,
        SUB: 4,
        img: `${MovsarYevloyev}`,
        age: 32,
        height: 170.18,
        weight: 66,
        debut: '20.04.19',
        armSpan: 184.15,
    },
    {
        name: 'Диего Лопес',
        nickname: `«Nightmare»`,
        rang: 2,
        victory: 27,
        defeat: 8,
        draw: 0,
        country: 'Бразилия',
        isChampion: false,
        KO: 11,
        DES: 4,
        SUB: 12,
        img: `${DiegoLopez}`,
        age: 31,
        height: 180.34,
        weight: 66.94,
        debut: '06.05.23',
        armSpan: 184.15,
    },
    {
        name: 'Лерон Мёрфи',
        nickname: `"The Miracle"`,
        rang: 3,
        victory: 17,
        defeat: 1,
        draw: 1,
        country: 'Англия',
        isChampion: false,
        KO: 8,
        DES: 9,
        SUB: 0,
        img: `${LeronMurphy}`,
        age: 34,
        height: 175.26,
        weight: 66.22,
        debut: '07.09.19',
        armSpan: 186.69,
    },
    {
        name: 'Яир Родригез',
        nickname: `«El Pantera»`,
        rang: 4,
        victory: 21,
        defeat: 5,
        draw: 0,
        country: 'Мексика',
        isChampion: false,
        KO: 8,
        DES: 8,
        SUB: 5,
        img: `${YairRodriguez}`,
        age: 33,
        height: 180.34,
        weight: 66.22,
        debut: '15.11.14',
        armSpan: 180.34,
    },
    {
        name: 'Алджэмейн Стерлинг',
        nickname: `«Funk Master»`,
        rang: 5,
        victory: 25,
        defeat: 5,
        draw: 0,
        country: 'США',
        isChampion: false,
        KO: 3,
        DES: 14,
        SUB: 8,
        img: `${AlgemaineSterling}`,
        age: 36,
        height: 170.18,
        weight: 69.4,
        debut: '22.02.14',
        armSpan: 180.34,
    },
    {
        name: 'Жан Силва',
        nickname: `«Lord»`,
        rang: 6,
        victory: 17,
        defeat: 3,
        draw: 0,
        country: 'Бразилия',
        isChampion: false,
        KO: 12,
        DES: 2,
        SUB: 3,
        img: `${JeanSilva}`,
        age: 29,
        height: 170.18,
        weight: 66.22,
        debut: '13.01.24',
        armSpan: 175.26,
    },
    {
        name: 'Юссеф Залал',
        nickname: `«The Moroccan Devil»`,
        rang: 7,
        victory: 18,
        defeat: 5,
        draw: 1,
        country: 'Марокко',
        isChampion: false,
        KO: 4,
        DES: 4,
        SUB: 10,
        img: `${YoussefZalal}`,
        age: 29,
        height: 177.8,
        weight: 66.22,
        debut: '08.02.20',
        armSpan: 182.88,
    },
    {
        name: 'Арнольд Аллен',
        nickname: `«Almighty»`,
        rang: 8,
        victory: 20,
        defeat: 4,
        draw: 0,
        country: 'Англия',
        isChampion: false,
        KO: 7,
        DES: 9,
        SUB: 4,
        img: `${ArnoldAllen}`,
        age: 32,
        height: 172.72,
        weight: 66,
        debut: '20.06.15',
        armSpan: 177.8,
    },
    {
        name: 'Стив Гарсия',
        nickname: `«Mean Machine»`,
        rang: 9,
        victory: 19,
        defeat: 5,
        draw: 0,
        country: 'США',
        isChampion: false,
        KO: 15,
        DES: 4,
        SUB: 0,
        img: `${SteveGarcia}`,
        age: 33,
        height: 182.88,
        weight: 66,
        debut: '29.02.20',
        armSpan: 190.5,
    },
    {
        name: 'Кевин Валльехос',
        nickname: `«El Chino»`,
        rang: 10,
        victory: 17,
        defeat: 1,
        draw: 0,
        country: 'Аргентина',
        isChampion: false,
        KO: 13,
        DES: 3,
        SUB: 2,
        img: `${KevinVallejos}`,
        age: 24,
        height: 170.18,
        weight: 65.77,
        debut: '15.03.25',
        armSpan: 172.72,
    },
    {
        name: 'Брайэн Ортега',
        nickname: `«T-City»`,
        rang: 11,
        victory: 15,
        defeat: 5,
        draw: 0,
        country: 'США',
        isChampion: false,
        KO: 3,
        DES: 5,
        SUB: 8,
        img: `${BrianOrtega}`,
        age: 35,
        height: 172.72,
        weight: 69.4,
        debut: '26.07.14',
        armSpan: 175.26,
    },
    {
        name: 'Мелкизаэл Коста',
        nickname: `«Melk Cauthy»`,
        rang: 12,
        victory: 25,
        defeat: 7,
        draw: 0,
        country: 'Бразилия',
        isChampion: false,
        KO: 9,
        DES: 9,
        SUB: 8,
        img: `${MelkizaelCosta}`,
        age: 29,
        height: 177.8,
        weight: 66,
        debut: '21.01.23',
        armSpan: 180.34,
    },
    {
        name: 'Аарон Пико',
        nickname: `«Cheeks»`,
        rang: 13,
        victory: 14,
        defeat: 5,
        draw: 0,
        country: 'США',
        isChampion: false,
        KO: 9,
        DES: 3,
        SUB: 2,
        img: `${AaronPico}`,
        age: 29,
        height: 172.72,
        weight: 65.77,
        debut: '26.07.25',
        armSpan: 179.07,
    },
    {
        name: 'Дэвид Онама',
        nickname: `«Silent Assassin»`,
        rang: 14,
        victory: 14,
        defeat: 3,
        draw: 0,
        country: 'Уганда',
        isChampion: false,
        KO: 7,
        DES: 4,
        SUB: 4,
        img: `${DavidOnama}`,
        age: 31,
        height: 180.34,
        weight: 66.22,
        debut: '23.10.21',
        armSpan: 187.96,
    },
    {
        name: 'Патрисио Питбуль',
        nickname: `«Pitbull»`,
        rang: 15,
        victory: 37,
        defeat: 9,
        draw: 0,
        country: 'Бразилия',
        isChampion: false,
        KO: 12,
        DES: 13,
        SUB: 12,
        img: `${PatricioPitbull}`,
        age: 38,
        height: 167.64,
        weight: 65.77,
        debut: '12.04.25',
        armSpan: 170.18,
    },
];