import type { fighterType } from "../Fighters.types";

export const flyWeight: fighterType[] = [
  {
    name: "Joshua Van",
    nickname: "The Fearless",
    rang: 0,
    victory: 16,
    defeat: 2,
    draw: 0,
    country: "MM",
    isChampion: true,
    KO: 8,
    DES: 6,
    SUB: 2,
    img: "/JoshuaWang.webp",
    age: 24,
    height: 165,
    weight: 56.7,
    debut: "24.06.23",
    armSpan: 165,
  },
  {
    name: "Alexandre Pantoja",
    nickname: "The Cannibal",
    rang: 1,
    victory: 30,
    defeat: 6,
    draw: 0,
    country: "BR",
    isChampion: false,
    KO: 8,
    DES: 10,
    SUB: 12,
    img: "/AlexanderPantoja.webp",
    age: 35,
    height: 165,
    weight: 56.7,
    debut: "29.01.17",
    armSpan: 170,
  },
  {
    name: "Manel Kape",
    nickname: "Starboy",
    rang: 2,
    victory: 22,
    defeat: 7,
    draw: 0,
    country: "AO",
    isChampion: false,
    KO: 14,
    DES: 3,
    SUB: 5,
    img: "/ManelCape.webp",
    age: 32,
    height: 165,
    weight: 56.7,
    debut: "06.02.21",
    armSpan: 173,
  },
  {
    name: "Tatsuro Taira",
    nickname: "The Best",
    rang: 3,
    victory: 18,
    defeat: 1,
    draw: 0,
    country: "JP",
    isChampion: false,
    KO: 6,
    DES: 4,
    SUB: 8,
    img: "/TatsuroTaira.webp",
    age: 26,
    height: 170,
    weight: 56.7,
    debut: "30.04.22",
    armSpan: 178,
  },
  {
    name: "Brandon Royval",
    nickname: "Row Dowg",
    rang: 4,
    victory: 17,
    defeat: 9,
    draw: 0,
    country: "US",
    isChampion: false,
    KO: 4,
    DES: 4,
    SUB: 9,
    img: "/BrandonRoyal.webp",
    age: 33,
    height: 175,
    weight: 56.7,
    debut: "30.05.20",
    armSpan: 173,
  },
  {
    name: "Kyoji Horiguchi",
    nickname: "The Supernova",
    rang: 5,
    victory: 36,
    defeat: 5,
    draw: 0,
    country: "JP",
    isChampion: false,
    KO: 15,
    DES: 15,
    SUB: 6,
    img: "/KyojiHoriguchi.webp",
    age: 35,
    height: 163,
    weight: 56.7,
    debut: "20.10.13",
    armSpan: 175,
  },
  {
    name: "Lone'er Kavanagh",
    nickname: null,
    rang: 6,
    victory: 10,
    defeat: 1,
    draw: 0,
    country: "GB",
    isChampion: false,
    KO: 4,
    DES: 5,
    SUB: 1,
    img: "/LoneKavanagh.webp",
    age: 26,
    height: 168,
    weight: 56.7,
    debut: "23.11.24",
    armSpan: 170,
  },
  {
    name: "Amir Albazi",
    nickname: "The Prince",
    rang: 7,
    victory: 17,
    defeat: 3,
    draw: 0,
    country: "IQ",
    isChampion: false,
    KO: 5,
    DES: 3,
    SUB: 9,
    img: "/AmirAlbazi.webp",
    age: 32,
    height: 165,
    weight: 56.7,
    debut: "18.07.20",
    armSpan: 173,
  },
  {
    name: "Asu Almabayev",
    nickname: "Zulfiqar",
    rang: 8,
    victory: 23,
    defeat: 3,
    draw: 0,
    country: "KZ",
    isChampion: false,
    KO: 3,
    DES: 10,
    SUB: 10,
    img: "/AsuAlmabaev.webp",
    age: 32,
    height: 163,
    weight: 56.7,
    debut: "05.08.23",
    armSpan: 165,
  },
  {
    name: "Brandon Moreno",
    nickname: "The Assassin Baby",
    rang: 9,
    victory: 23,
    defeat: 10,
    draw: 2,
    country: "MX",
    isChampion: false,
    KO: 5,
    DES: 7,
    SUB: 11,
    img: "/BrandonMoreno.webp",
    age: 32,
    height: 170,
    weight: 56.7,
    debut: "02.10.16",
    armSpan: 178,
  },
  {
    name: "Steve Erceg",
    nickname: "Astro Boy",
    rang: 10,
    victory: 14,
    defeat: 4,
    draw: 0,
    country: "AU",
    isChampion: false,
    KO: 2,
    DES: 6,
    SUB: 6,
    img: "/SteveErceg.webp",
    age: 30,
    height: 173,
    weight: 56.7,
    debut: "20.05.23",
    armSpan: 173,
  },
  {
    name: "Alex Perez",
    nickname: "The Decision",
    rang: 11,
    victory: 26,
    defeat: 10,
    draw: 0,
    country: "US",
    isChampion: false,
    KO: 7,
    DES: 12,
    SUB: 7,
    img: "/AlexPerez.webp",
    age: 34,
    height: 168,
    weight: 56.7,
    debut: "08.08.17",
    armSpan: 166,
  },
  {
    name: "Tim Elliott",
    nickname: "Haitian Sensation",
    rang: 12,
    victory: 23,
    defeat: 14,
    draw: 1,
    country: "US",
    isChampion: false,
    KO: 3,
    DES: 12,
    SUB: 8,
    img: "/TimElliott.webp",
    age: 39,
    height: 170,
    weight: 56.7,
    debut: "05.05.12",
    armSpan: 168,
  },
  {
    name: "Charles Johnson",
    nickname: "InnerG",
    rang: 13,
    victory: 19,
    defeat: 10,
    draw: 0,
    country: "US",
    isChampion: false,
    KO: 8,
    DES: 8,
    SUB: 3,
    img: "/CharlesJohnson.webp",
    age: 35,
    height: 175,
    weight: 56.7,
    debut: "23.07.22",
    armSpan: 178,
  },
  {
    name: "Tagir Ulanbekov",
    nickname: null,
    rang: 14,
    victory: 17,
    defeat: 3,
    draw: 0,
    country: "RU",
    isChampion: false,
    KO: 1,
    DES: 8,
    SUB: 8,
    img: "/TagirUlanbekov.webp",
    age: 34,
    height: 170,
    weight: 56.7,
    debut: "10.10.20",
    armSpan: 178,
  },
  {
    name: "Bruno Silva",
    nickname: "Blindado",
    rang: 15,
    victory: 15,
    defeat: 8,
    draw: 3,
    country: "BR",
    isChampion: false,
    KO: 6,
    DES: 4,
    SUB: 5,
    img: "/BrunoSilva.webp",
    age: 36,
    height: 163,
    weight: 56.7,
    debut: "07.09.19",
    armSpan: 165,
  },
];