import type { fighterType } from "../Fighters.types";
import JoshuaWang from "../../../../../public/JoshuaWang.png";
import AlexanderPantoja from "../../../../../public/AlexanderPantoja.png";
import ManelCape from "../../../../../public/ManelCape.png";
import TatsuroTaira from "../../../../../public/TatsuroTaira.png";
import BrandonRoyal from "../../../../../public/BrandonRoyal.png";
import KyojiHoriguchi from "../../../../../public/KyojiHoriguchi.png";
import LoneKavanagh from "../../../../../public/LoneKavanagh.png";
import AmirAlbazi from "../../../../../public/AmirAlbazi.png";
import AsuAlmabaev from "../../../../../public/AsuAlmabaev.png";
import BrandonMoreno from "../../../../../public/BrandonMoreno.png";
import AlexPerez from "../../../../../public/AlexPerez.png";
import SteveErceg from "../../../../../public/SteveErceg.png";
import CharlesJohnson from "../../../../../public/CharlesJohnson.png";
import BrunoSilva from "../../../../../public/BrunoSilva.png";
import TagirUlanbekov from "../../../../../public/TagirUlanbekov.png";
import TimElliott from "../../../../../public/TimElliott.png";

export const flyWeight: fighterType[] = [
    {
        name: 'Джошуа Ван',
        nickname: `«The Fearless»`,
        rang: 0,
        victory: 16,
        defeat: 2,
        draw: 0,
        country: 'Мьянма',
        isChampion: true,
        KO: 8,
        DES: 6,
        SUB: 2,
        img: `${JoshuaWang}`,
        age: 24,
        height: 165.1,
        weight: 56.47,
        debut: '24.06.23',
        armSpan: 165.1,
    },
    {
        name: 'Александр Пантожа',
        nickname: `«The Cannibal»`,
        rang: 1,
        victory: 30,
        defeat: 6,
        draw: 0,
        country: 'Бразилия',
        isChampion: false,
        KO: 8,
        DES: 10,
        SUB: 12,
        img: `${AlexanderPantoja}`,
        age: 35,
        height: 165.1,
        weight: 56.7,
        debut: '29.01.17',
        armSpan: 170.18,
    },
    {
        name: 'Манель Кейпе',
        nickname: `«Starboy»`,
        rang: 2,
        victory: 22,
        defeat: 7,
        draw: 0,
        country: 'Ангола',
        isChampion: false,
        KO: 14,
        DES: 3,
        SUB: 5,
        img: `${ManelCape}`,
        age: 32,
        height: 165.1,
        weight: 57.15,
        debut: '06.02.21',
        armSpan: 172.72,
    },
    {
        name: 'Татсуро Таира',
        nickname: `«The Best»`,
        rang: 3,
        victory: 18,
        defeat: 1,
        draw: 0,
        country: 'Япония',
        isChampion: false,
        KO: 6,
        DES: 4,
        SUB: 8,
        img: `${TatsuroTaira}`,
        age: 26,
        height: 170.18,
        weight: 57.15,
        debut: '30.04.22',
        armSpan: 177.8,
    },
    {
        name: 'Брэндон Ройвал',
        nickname: `«Row Dowg»`,
        rang: 4,
        victory: 17,
        defeat: 9,
        draw: 0,
        country: 'США',
        isChampion: false,
        KO: 4,
        DES: 4,
        SUB: 9,
        img: `${BrandonRoyal}`,
        age: 33,
        height: 175.26,
        weight: 57.15,
        debut: '30.05.20',
        armSpan: 172.72,
    },
    {
        name: 'Кёдзи Хоригути',
        nickname: `«The Supernova»`,
        rang: 5,
        victory: 36,
        defeat: 5,
        draw: 0,
        country: 'Япония',
        isChampion: false,
        KO: 15,
        DES: 15,
        SUB: 6,
        img: `${KyojiHoriguchi}`,
        age: 35,
        height: 162.56,
        weight: 56.7,
        debut: '20.10.13',
        armSpan: 175.26,
    },
    {
        name: 'Лонэ Кавана',
        nickname: null,
        rang: 6,
        victory: 10,
        defeat: 1,
        draw: 0,
        country: 'Англия',
        isChampion: false,
        KO: 4,
        DES: 5,
        SUB: 1,
        img: `${LoneKavanagh}`,
        age: 26,
        height: 167.64,
        weight: 57.15,
        debut: '23.11.24',
        armSpan: 170.18,
    },
    {
        name: 'Амир Альбази',
        nickname: `«The Prince»`,
        rang: 7,
        victory: 17,
        defeat: 3,
        draw: 0,
        country: 'Ирак',
        isChampion: false,
        KO: 5,
        DES: 3,
        SUB: 9,
        img: `${AmirAlbazi}`,
        age: 32,
        height: 165.1,
        weight: 56.93,
        debut: '18.07.20',
        armSpan: 172.72,
    },
    {
        name: 'Асу Алмабаев',
        nickname: `«Zulfiqar»`,
        rang: 8,
        victory: 23,
        defeat: 3,
        draw: 0,
        country: 'Казахстан',
        isChampion: false,
        KO: 3,
        DES: 10,
        SUB: 10,
        img: `${AsuAlmabaev}`,
        age: 32,
        height: 162.56,
        weight: 56.93,
        debut: '05.08.23',
        armSpan: 165.1,
    },
    {
        name: 'Брэндон Морено',
        nickname: `«The Assassin Baby»`,
        rang: 9,
        victory: 23,
        defeat: 10,
        draw: 2,
        country: 'Мексика',
        isChampion: false,
        KO: 5,
        DES: 7,
        SUB: 11,
        img: `${BrandonMoreno}`,
        age: 32,
        height: 170.18,
        weight: 56.7,
        debut: '02.10.16',
        armSpan: 177.8,
    },
    {
        name: 'Стив Эрцег',
        nickname: `«Astro Boy»`,
        rang: 10,
        victory: 14,
        defeat: 4,
        draw: 0,
        country: 'Австралия',
        isChampion: false,
        KO: 2,
        DES: 6,
        SUB: 6,
        img: `${SteveErceg}`,
        age: 30,
        height: 172.72,
        weight: 61.46,
        debut: '20.05.23',
        armSpan: 172.72,
    },
    {
        name: 'Алекс Перез',
        nickname: `«The Decision»`,
        rang: 11,
        victory: 26,
        defeat: 10,
        draw: 0,
        country: 'США',
        isChampion: false,
        KO: 7,
        DES: 12,
        SUB: 7,
        img: `${AlexPerez}`,
        age: 34,
        height: 167.64,
        weight: 58.29,
        debut: '08.08.17',
        armSpan: 166.37,
    },
    {
        name: 'Тим Эллиотт',
        nickname: `«Haitian Sensation»`,
        rang: 12,
        victory: 23,
        defeat: 14,
        draw: 1,
        country: 'США',
        isChampion: false,
        KO: 3,
        DES: 12,
        SUB: 8,
        img: `${TimElliott}`,
        age: 39,
        height: 170.18,
        weight: 57.15,
        debut: '05.05.12',
        armSpan: 167.64,
    },
    {
        name: 'Чарльс Джонсон',
        nickname: `«InnerG»`,
        rang: 13,
        victory: 19,
        defeat: 10,
        draw: 0,
        country: 'США',
        isChampion: false,
        KO: 8,
        DES: 8,
        SUB: 3,
        img: `${CharlesJohnson}`,
        age: 35,
        height: 175.26,
        weight: 57.15,
        debut: '23.07.22',
        armSpan: 177.8,
    },
    {
        name: 'Тагир Уланбеков',
        nickname: null,
        rang: 14,
        victory: 17,
        defeat: 3,
        draw: 0,
        country: 'Россия',
        isChampion: false,
        KO: 1,
        DES: 8,
        SUB: 8,
        img: `${TagirUlanbekov}`,
        age: 34,
        height: 170.18,
        weight: 56.93,
        debut: '10.10.20',
        armSpan: 177.8,
    },
    {
        name: 'Бруно Силва',
        nickname: `«Blindado»`,
        rang: 15,
        victory: 15,
        defeat: 8,
        draw: 3,
        country: 'Бразилия',
        isChampion: false,
        KO: 6,
        DES: 4,
        SUB: 5,
        img: `${BrunoSilva}`,
        age: 36,
        height: 162.56,
        weight: 56.93,
        debut: '07.09.19',
        armSpan: 165.1,
    },

];