import type { fighterType } from "../Fighters.types";
import JoshuaWang from "../../../../../public/JoshuaWang.png";
import AlexanderPantoja from "../../../../../public/AlexanderPantoja.png";
import ManelCape from "../../../../../public/ManelCape.png";
import TatsuroTaira from "../../../../../public/TatsuroTaira.png";
import BrandonRoyal from "../../../../../public/BrandonRoyal.png";
import KyojiHoriguchi from "../../../../../public/KyojiHoriguchi.png";
import LoneKavanagh from "../../../../../public/LoneKavanagh.png";
import AmirAlbazi from "../../../../../public/AmirAlbazi.png";
import AsuAlmabaev from "../../../../../public/AsuAlmabaev.png";
import BrandonMoreno from "../../../../../public/BrandonMoreno.png";
import AlexPerez from "../../../../../public/AlexPerez.png";
import SteveErceg from "../../../../../public/SteveErceg.png";
import CharlesJohnson from "../../../../../public/CharlesJohnson.png";
import BrunoSilva from "../../../../../public/BrunoSilva.png";
import TagirUlanbekov from "../../../../../public/TagirUlanbekov.png";
import TimElliott from "../../../../../public/TimElliott.png";

export const flyWeight: fighterType[] = [ 
    {
        name: 'Джошуа Ван',
        nickname: null,
        rang: 0,
        victory: 16,
        defeat: 2,
        draw: 0,
        country: 'Мьянма',
        isChampion: true,
        KO: 8,
        DES: 6,
        SUB: 2,
        img: `${JoshuaWang}`
    },
    {
        name: 'Александр Пантожа',
        nickname: `"The Cannibal"`,
        rang: 1,
        victory: 30,
        defeat: 6,
        draw: 0,
        country: 'Бразилия',
        isChampion: false,
        KO: 8,
        DES: 10,
        SUB: 12,
        img: `${AlexanderPantoja}`
    },
    {
        name: 'Манель Кейпе',
        nickname: null,
        rang: 2,
        victory: 22,
        defeat: 7,
        draw: 0,
        country: 'Ангола',
        isChampion: false,
        KO: 14,
        DES: 3,
        SUB: 5,
        img: `${ManelCape}`
    },
    {
        name: 'Татсуро Таира',
        nickname: null,
        rang: 3,
        victory: 18,
        defeat: 1,
        draw: 0,
        country: 'Япония',
        isChampion: false,
        KO: 6,
        DES: 4,
        SUB: 8,
        img: `${TatsuroTaira}`
    },
    {
        name: 'Брэндон Ройвал',
        nickname: null,
        rang: 4,
        victory: 17,
        defeat: 9,
        draw: 0,
        country: 'США',
        isChampion: false,
        KO: 4,
        DES: 4,
        SUB: 9,
        img: `${BrandonRoyal}`,
    },
    {
        name: 'Киоджи Хоригучи',
        nickname: null,
        rang: 5,
        victory: 36,
        defeat: 5,
        draw: 0,
        country: 'Япония',
        isChampion: false,
        KO: 15,
        DES: 15,
        SUB: 6,
        img: `${KyojiHoriguchi}`,
    },
    {
        name: 'Лонэ Кавана',
        nickname: null,
        rang: 6,
        victory: 10,
        defeat: 1,
        draw: 0,
        country: 'England',
        isChampion: false,
        KO: 4,
        DES: 5,
        SUB: 1,
        img: `${LoneKavanagh}`,
    },
    {
        name: 'Амир Альбази',
        nickname: null,
        rang: 7,
        victory: 17,
        defeat: 3,
        draw: 0,
        country: 'Ирак',
        isChampion: false,
        KO: 5,
        DES: 3,
        SUB: 9,
        img: `${AmirAlbazi}`,
    },
    {
        name: 'Асу Алмабаев',
        nickname: null,
        rang: 8,
        victory: 23,
        defeat: 3,
        draw: 0,
        country: 'Казахстан',
        isChampion: false,
        KO: 3,
        DES: 10,
        SUB: 10,
        img: `${AsuAlmabaev}`,
    },
    {
        name: 'Брэндон Морено',
        nickname: `"The Assassin Baby"`,
        rang: 9,
        victory: 23,
        defeat: 10,
        draw: 2,
        country: 'Мексика',
        isChampion: false,
        KO: 5,
        DES: 7,
        SUB: 11,
        img: `${BrandonMoreno}`,
    },
    {
        name: 'Алекс Перез',
        nickname: null,
        rang: 10,
        victory: 26,
        defeat: 10,
        draw: 0,
        country: 'США',
        isChampion: false,
        KO: 7,
        DES: 12,
        SUB: 7,
        img: `${AlexPerez}`,
    },
    {
        name: 'Тим Эллиотт',
        nickname: null,
        rang: 11,
        victory: 21,
        defeat: 13,
        draw: 1,
        country: 'США',
        isChampion: false,
        KO: 3,
        DES: 11,
        SUB: 8,
        img: `${TimElliott}`,
    },
    {
        name: 'Стив Эрцег',
        nickname: null,
        rang: 12,
        victory: 13,
        defeat: 4,
        draw: 0,
        country: 'Австралия',
        isChampion: false,
        KO: 2,
        DES: 5,
        SUB: 6,
        img: `${SteveErceg}`,
    },
    {
        name: 'Чарльс Джонсон',
        nickname: null,
        rang: 13,
        victory: 19,
        defeat: 10,
        draw: 0,
        country: 'США',
        isChampion: false,
        KO: 8,
        DES: 8,
        SUB: 3,
        img: `${CharlesJohnson}`,
    },
    {
        name: 'Тагир Уланбеков',
        nickname: null,
        rang: 14,
        victory: 17,
        defeat: 3,
        draw: 0,
        country: 'Россия',
        isChampion: false,
        KO: 1,
        DES: 8,
        SUB: 8,
        img: `${TagirUlanbekov}`,
    },
    {
        name: 'Бруно Силва',
        nickname: null,
        rang: 15,
        victory: 15,
        defeat: 8,
        draw: 3,
        country: 'Бразилия',
        isChampion: false,
        KO: 6,
        DES: 4,
        SUB: 5,
        img: `${BrunoSilva}`,
    },

];