import type { fighterType } from "../Fighters.types";

export const heavyWeight: fighterType[] = [
  {
    name: "Tom Aspinall",
    nickname: "The Honey Badger",
    rang: 0,
    victory: 15,
    defeat: 3,
    draw: 0,
    country: "GB",
    isChampion: true,
    KO: 12,
    DES: 0,
    SUB: 3,
    img: "/TomAspinall.webp",
    age: 33,
    height: 196,
    weight: 120.2,
    debut: "21.03.20",
    armSpan: 198,
  },
  {
    name: "Ciryl Gane",
    nickname: "Bon Gamin",
    rang: 1,
    victory: 13,
    defeat: 2,
    draw: 0,
    country: "FR",
    isChampion: false,
    KO: 6,
    DES: 4,
    SUB: 3,
    img: "/CyrilGan.webp",
    age: 36,
    height: 193,
    weight: 120.2,
    debut: "10.08.19",
    armSpan: 206,
  },
  {
    name: "Alexander Volkov",
    nickname: "Drago",
    rang: 2,
    victory: 40,
    defeat: 11,
    draw: 0,
    country: "RU",
    isChampion: false,
    KO: 24,
    DES: 12,
    SUB: 4,
    img: "/AlexanderVolkov.webp",
    age: 37,
    height: 201,
    weight: 120.2,
    debut: "19.11.16",
    armSpan: 203,
  },
  {
    name: "Sergei Pavlovich",
    nickname: null,
    rang: 3,
    victory: 20,
    defeat: 3,
    draw: 0,
    country: "RU",
    isChampion: false,
    KO: 15,
    DES: 5,
    SUB: 0,
    img: "/SergeyPavlovich.webp",
    age: 33,
    height: 191,
    weight: 120.2,
    debut: "24.11.18",
    armSpan: 213,
  },
  {
    name: "Waldo Cortes-Acosta",
    nickname: "Salsa Boy",
    rang: 4,
    victory: 17,
    defeat: 3,
    draw: 0,
    country: "DO",
    isChampion: false,
    KO: 9,
    DES: 7,
    SUB: 1,
    img: "/ValdoCortezAcosta.webp",
    age: 34,
    height: 193,
    weight: 120.2,
    debut: "29.10.22",
    armSpan: 198,
  },
  {
    name: "Josh Hokit",
    nickname: "The Incredible Hok",
    rang: 5,
    victory: 9,
    defeat: 0,
    draw: 0,
    country: "US",
    isChampion: false,
    KO: 5,
    DES: 1,
    SUB: 3,
    img: "/JoshHokit.webp",
    age: 28,
    height: 185,
    weight: 120.2,
    debut: "08.11.25",
    armSpan: 187,
  },
  {
    name: "Serghei Spivac",
    nickname: "Polar Bear",
    rang: 6,
    victory: 18,
    defeat: 6,
    draw: 0,
    country: "MD",
    isChampion: false,
    KO: 7,
    DES: 3,
    SUB: 8,
    img: "/SergeySpivak.webp",
    age: 31,
    height: 191,
    weight: 120.2,
    debut: "04.05.19",
    armSpan: 198,
  },
  {
    name: "Curtis Blaydes",
    nickname: "Razor",
    rang: 7,
    victory: 19,
    defeat: 6,
    draw: 0,
    country: "US",
    isChampion: false,
    KO: 13,
    DES: 6,
    SUB: 0,
    img: "/CurtisBlades.webp",
    age: 35,
    height: 193,
    weight: 120.2,
    debut: "10.04.16",
    armSpan: 203,
  },
  {
    name: "Rizvan Kuniev",
    nickname: null,
    rang: 8,
    victory: 12,
    defeat: 3,
    draw: 1,
    country: "RU",
    isChampion: false,
    KO: 6,
    DES: 4,
    SUB: 2,
    img: "/RizvanKuniev.webp",
    age: 33,
    height: 193,
    weight: 120.2,
    debut: "22.02.25",
    armSpan: 193,
  },
  {
    name: "Derrick Lewis",
    nickname: "The Black Beast",
    rang: 9,
    victory: 29,
    defeat: 13,
    draw: 0,
    country: "US",
    isChampion: false,
    KO: 24,
    DES: 4,
    SUB: 1,
    img: "/DerrickLewis.webp",
    age: 41,
    height: 191,
    weight: 120.2,
    debut: "19.04.14",
    armSpan: 201,
  },
  {
    name: "Tyrell Fortune",
    nickname: null,
    rang: 10,
    victory: 18,
    defeat: 3,
    draw: 0,
    country: "US",
    isChampion: false,
    KO: 11,
    DES: 5,
    SUB: 1,
    img: "/TyrellFortune.webp",
    age: 35,
    height: 191,
    weight: 120.2,
    debut: "28.03.26",
    armSpan: 196,
  },
  {
    name: "Ante Delija",
    nickname: "Walking Trouble",
    rang: 11,
    victory: 26,
    defeat: 8,
    draw: 0,
    country: "HR",
    isChampion: false,
    KO: 12,
    DES: 7,
    SUB: 7,
    img: "/AnteDelia.webp",
    age: 35,
    height: 192,
    weight: 120.2,
    debut: "17.10.20",
    armSpan: 198,
  },
  {
    name: "Marcin Tybura",
    nickname: "Tybur",
    rang: 12,
    victory: 27,
    defeat: 11,
    draw: 0,
    country: "PL",
    isChampion: false,
    KO: 10,
    DES: 10,
    SUB: 7,
    img: "/MarcinTybura.webp",
    age: 40,
    height: 191,
    weight: 120.2,
    debut: "10.04.16",
    armSpan: 198,
  },
  {
    name: "Valter Walker",
    nickname: "The Clean Monster",
    rang: 13,
    victory: 15,
    defeat: 1,
    draw: 0,
    country: "BR",
    isChampion: false,
    KO: 6,
    DES: 4,
    SUB: 5,
    img: "/WalterWalker.webp",
    age: 28,
    height: 198,
    weight: 120.2,
    debut: "06.04.24",
    armSpan: 199,
  },
  {
    name: "Brando Pericic",
    nickname: "The Balkan Bear",
    rang: 14,
    victory: 7,
    defeat: 1,
    draw: 0,
    country: "AU",
    isChampion: false,
    KO: 6,
    DES: 0,
    SUB: 1,
    img: "/BrandoPericic.webp",
    age: 31,
    height: 196,
    weight: 120.2,
    debut: "27.09.25",
    armSpan: 202,
  },
  {
    name: "Tallison Teixeira",
    nickname: "Chicane",
    rang: 15,
    victory: 9,
    defeat: 1,
    draw: 0,
    country: "BR",
    isChampion: false,
    KO: 7,
    DES: 1,
    SUB: 1,
    img: "/TallisonTeixeira.webp",
    age: 26,
    height: 201,
    weight: 120.2,
    debut: "08.02.25",
    armSpan: 211,
  },
];