import type { fighterType } from "../Fighters.types";
import TomAspinall from "../../../../../public/TomAspinall.png";
import CyrilGan from "../../../../../public/CyrilGan.png";
import AlexanderVolkov from "../../../../../public/AlexanderVolkov.png";
import SergeyPavlovich from "../../../../../public/SergeyPavlovich.png";
import ValdoCortezAcosta from "../../../../../public/ValdoCortez-Acosta.png";
import JoshHokit from "../../../../../public/JoshHokit.png";
import SergeySpivak from "../../../../../public/SergeySpivak.png";
import CurtisBlades from "../../../../../public/CurtisBlades.png";
import RizvanKuniev from "../../../../../public/RizvanKuniev.png";
import DerrickLewis from "../../../../../public/DerrickLewis.png";
import TyrellFortune from "../../../../../public/TyrellFortune.png";
import AnteDelia from "../../../../../public/AnteDelia.png";
import MarcinTybura from "../../../../../public/MarcinTybura.png";
import WalterWalker from "../../../../../public/WalterWalker.png";
import BrandoPericic from "../../../../../public/BrandoPericic.png";
import TallisonTeixeira from "../../../../../public/TallisonTeixeira.png";

export const heavyWeight: fighterType[] = [
    {
        name: 'Том Аспинэлл',
        nickname: `«The Honey Badger»`,
        rang: 0,
        victory: 15,
        defeat: 3,
        draw: 0,
        country: 'Англия',
        isChampion: true,
        KO: 12,
        DES: 0,
        SUB: 3,
        img: `${TomAspinall}`,
        age: 33,
        height: 195.58,
        weight: 115.21,
        debut: '21.03.20',
        armSpan: 198.12,
    },
    {
        name: 'Сирил Ган',
        nickname: `«Bon Gamin»`,
        rang: 1,
        victory: 13,
        defeat: 2,
        draw: 0,
        country: 'Франция',
        isChampion: false,
        KO: 6,
        DES: 4,
        SUB: 3,
        img: `${CyrilGan}`,
        age: 36,
        height: 193.04,
        weight: 112.26,
        debut: '10.08.19',
        armSpan: 205.74,
    },
    {
        name: 'Александр Волков',
        nickname: `«Drago»`,
        rang: 2,
        victory: 40,
        defeat: 11,
        draw: 0,
        country: 'Россия',
        isChampion: false,
        KO: 24,
        DES: 12,
        SUB: 4,
        img: `${AlexanderVolkov}`,
        age: 37,
        height: 200.66,
        weight: 118.61,
        debut: '19.11.16',
        armSpan: 203.2,
    },
    {
        name: 'Сергей Павлович',
        nickname: null,
        rang: 3,
        victory: 20,
        defeat: 3,
        draw: 0,
        country: 'Россия',
        isChampion: false,
        KO: 15,
        DES: 5,
        SUB: 0,
        img: `${SergeyPavlovich}`,
        age: 33,
        height: 190.5,
        weight: 115.89,
        debut: '24.11.18',
        armSpan: 213.36,
    },
    {
        name: 'Валдо Кортес-Акоста',
        nickname: `«Salsa Boy»`,
        rang: 4,
        victory: 17,
        defeat: 3,
        draw: 0,
        country: 'Доминикан',
        isChampion: false,
        KO: 9,
        DES: 7,
        SUB: 1,
        img: `${ValdoCortezAcosta}`,
        age: 34,
        height: 193.04,
        weight: 118.84,
        debut: '29.10.22',
        armSpan: 198.12,
    },
    {
        name: 'Джош Хокит',
        nickname: `«The Incredible Hok»`,
        rang: 5,
        victory: 9,
        defeat: 0,
        draw: 0,
        country: 'США',
        isChampion: false,
        KO: 5,
        DES: 1,
        SUB: 3,
        img: `${JoshHokit}`,
        age: 28,
        height: 185.42,
        weight: 106.37,
        debut: '08.11.25',
        armSpan: 186.69,
    },
    {
        name: 'Сергей Спивак',
        nickname: `«Polar Bear»`,
        rang: 6,
        victory: 18,
        defeat: 6,
        draw: 0,
        country: 'Молдова',
        isChampion: false,
        KO: 7,
        DES: 3,
        SUB: 8,
        img: `${SergeySpivak}`,
        age: 31,
        height: 190.5,
        weight: 113.85,
        debut: '04.05.19',
        armSpan: 198.12,
    },
    {
        name: 'Кёртис Блэйдс',
        nickname: `«Razor»`,
        rang: 7,
        victory: 19,
        defeat: 6,
        draw: 0,
        country: 'США',
        isChampion: false,
        KO: 13,
        DES: 6,
        SUB: 0,
        img: `${CurtisBlades}`,
        age: 35,
        height: 193.04,
        weight: 117.03,
        debut: '10.04.16',
        armSpan: 203.2,
    },
    {
        name: 'Ризван Куниев',
        nickname: null,
        rang: 8,
        victory: 12,
        defeat: 3,
        draw: 1,
        country: 'Россия',
        isChampion: false,
        KO: 6,
        DES: 4,
        SUB: 2,
        img: `${RizvanKuniev}`,
        age: 33,
        height: 193.04,
        weight: 108.86,
        debut: '22.02.25',
        armSpan: 193.04,
    },
    {
        name: 'Деррик Льюис',
        nickname: `«The Black Beast»`,
        rang: 9,
        victory: 29,
        defeat: 13,
        draw: 0,
        country: 'США',
        isChampion: false,
        KO: 24,
        DES: 4,
        SUB: 1,
        img: `${DerrickLewis}`,
        age: 41,
        height: 190.5,
        weight: 119.52,
        debut: '19.04.14',
        armSpan: 200.66,
    },
    {
        name: 'Тайрелл Форчен',
        nickname: null,
        rang: 10,
        victory: 18,
        defeat: 3,
        draw: 0,
        country: 'США',
        isChampion: false,
        KO: 11,
        DES: 5,
        SUB: 1,
        img: `${TyrellFortune}`,
        age: 35,
        height: 190.5,
        weight: 113.4,
        debut: '28.03.26',
        armSpan: 196,
    },
    {
        name: 'Анте Делия',
        nickname: `«Walking Trouble»`,
        rang: 11,
        victory: 26,
        defeat: 8,
        draw: 0,
        country: 'Хорватия',
        isChampion: false,
        KO: 12,
        DES: 7,
        SUB: 7,
        img: `${AnteDelia}`,
        age: 35,
        height: 191.77,
        weight: 107.73,
        debut: '17.10.20',
        armSpan: 198.12,
    },
    {
        name: 'Марчин Тыбура',
        nickname: `«Tybur»`,
        rang: 12,
        victory: 27,
        defeat: 11,
        draw: 0,
        country: 'Польша',
        isChampion: false,
        KO: 10,
        DES: 10,
        SUB: 7,
        img: `${MarcinTybura}`,
        age: 40,
        height: 190.5,
        weight: 116.12,
        debut: '10.04.16',
        armSpan: 198.12,
    },
    {
        name: 'Вальтер Уокер',
        nickname: `«The Clean Monster»`,
        rang: 13,
        victory: 15,
        defeat: 1,
        draw: 0,
        country: 'Бразилия',
        isChampion: false,
        KO: 6,
        DES: 4,
        SUB: 5,
        img: `${WalterWalker}`,
        age: 28,
        height: 198.12,
        weight: 110.68,
        debut: '06.04.24',
        armSpan: 199.39,
    },
    {
        name: 'Брэндо Перичич',
        nickname: `«The Balkan Bear»`,
        rang: 14,
        victory: 7,
        defeat: 1,
        draw: 0,
        country: 'Австралия',
        isChampion: false,
        KO: 6,
        DES: 0,
        SUB: 1,
        img: `${BrandoPericic}`,
        age: 31,
        height: 195.58,
        weight: 118.39,
        debut: '27.09.25',
        armSpan: 201.93,
    },
    {
        name: 'Таллисон Тейшейра',
        nickname: `«Chicane»`,
        rang: 15,
        victory: 9,
        defeat: 1,
        draw: 0,
        country: 'Бразилия',
        isChampion: false,
        KO: 7,
        DES: 1,
        SUB: 1,
        img: `${TallisonTeixeira}`,
        age: 26,
        height: 200.66,
        weight: 117.03,
        debut: '08.02.25',
        armSpan: 210.82,
    },
];