import type { fighterType } from "../Fighters.types";
import IlyaTopuria from "../../../../../public/IlyaTopuria.png";
import JustinGage from "../../../../../public/JustinGage.png";
import ArmanTsarukyan from "../../../../../public/ArmanTsarukyan.png";
import CharlesOliveira from "../../../../../public/CharlesOliveira.png";
import MaxHolloway from "../../../../../public/MaxHolloway.png";
import BenoitSaintDenis from "../../../../../public/BenoitSaintDenis.png";
import PaddyPimblett from "../../../../../public/PaddyPimblett.png";
import MateuszGamrot from "../../../../../public/MateuszGamrot.png";
import DanHooker from "../../../../../public/DanHooker.png";
import RenatoMoikano from "../../../../../public/RenatoMoikano.png";
import MauricioRuffi from "../../../../../public/MauricioRuffi.png";
import RafaelFiziev from "../../../../../public/RafaelFiziev.png";
import BeneelDariusz from "../../../../../public/BeneelDariusz.png";
import MichaelChandler from "../../../../../public/MichaelChandler.png";
import FaresZiam from "../../../../../public/FaresZiam.png";
import QuillanSalkild from "../../../../../public/QuillanSalkild.png";

export const lightWeight: fighterType[] = [
    {
        name: "Ilia Topuria",
        nickname: "La Leyenda",
        rang: 0,
        victory: 17,
        defeat: 0,
        draw: 0,
        country: "ES",
        isChampion: true,
        KO: 7,
        DES: 2,
        SUB: 8,
        img: `${IlyaTopuria}`,
        age: 29,
        height: 170,
        weight: 70.3,
        debut: "10.10.20",
        armSpan: 175,
    },
    {
        name: "Justin Gaethje",
        nickname: "The Highlight",
        rang: 1,
        victory: 27,
        defeat: 5,
        draw: 0,
        country: "US",
        isChampion: false,
        KO: 20,
        DES: 6,
        SUB: 1,
        img: `${JustinGage}`,
        age: 37,
        height: 180,
        weight: 70.3,
        debut: "08.07.17",
        armSpan: 178,
    },
    {
        name: "Arman Tsarukyan",
        nickname: "Tough Guy",
        rang: 2,
        victory: 23,
        defeat: 3,
        draw: 0,
        country: "GE",
        isChampion: false,
        KO: 9,
        DES: 8,
        SUB: 6,
        img: `${ArmanTsarukyan}`,
        age: 29,
        height: 170,
        weight: 70.3,
        debut: "20.04.19",
        armSpan: 184,
    },
    {
        name: "Charles Oliveira",
        nickname: "Do Bronx",
        rang: 3,
        victory: 37,
        defeat: 11,
        draw: 0,
        country: "BR",
        isChampion: false,
        KO: 10,
        DES: 5,
        SUB: 22,
        img: `${CharlesOliveira}`,
        age: 36,
        height: 178,
        weight: 70.3,
        debut: "01.08.10",
        armSpan: 188,
    },
    {
        name: "Max Holloway",
        nickname: "Blessed",
        rang: 4,
        victory: 27,
        defeat: 9,
        draw: 0,
        country: "US",
        isChampion: false,
        KO: 12,
        DES: 13,
        SUB: 2,
        img: `${MaxHolloway}`,
        age: 34,
        height: 180,
        weight: 70.3,
        debut: "04.02.12",
        armSpan: 175,
    },
    {
        name: "Benoit Saint Denis",
        nickname: "God of War",
        rang: 5,
        victory: 17,
        defeat: 3,
        draw: 0,
        country: "FR",
        isChampion: false,
        KO: 6,
        DES: 0,
        SUB: 11,
        img: `${BenoitSaintDenis}`,
        age: 30,
        height: 180,
        weight: 70.3,
        debut: "30.10.21",
        armSpan: 185,
    },
    {
        name: "Paddy Pimblett",
        nickname: "The Baddy",
        rang: 6,
        victory: 23,
        defeat: 4,
        draw: 0,
        country: "GB",
        isChampion: false,
        KO: 7,
        DES: 6,
        SUB: 10,
        img: `${PaddyPimblett}`,
        age: 31,
        height: 178,
        weight: 70.3,
        debut: "04.09.21",
        armSpan: 185,
    },
    {
        name: "Mateusz Gamrot",
        nickname: "Gamer",
        rang: 7,
        victory: 26,
        defeat: 4,
        draw: 0,
        country: "PL",
        isChampion: false,
        KO: 8,
        DES: 12,
        SUB: 6,
        img: `${MateuszGamrot}`,
        age: 35,
        height: 178,
        weight: 70.3,
        debut: "17.10.20",
        armSpan: 179,
    },
    {
        name: "Dan Hooker",
        nickname: "The Hangman",
        rang: 8,
        victory: 24,
        defeat: 14,
        draw: 0,
        country: "NZ",
        isChampion: false,
        KO: 11,
        DES: 6,
        SUB: 7,
        img: `${DanHooker}`,
        age: 36,
        height: 183,
        weight: 70.3,
        debut: "28.06.14",
        armSpan: 191,
    },
    {
        name: "Renato Moicano",
        nickname: "Money Moicano",
        rang: 9,
        victory: 21,
        defeat: 7,
        draw: 1,
        country: "BR",
        isChampion: false,
        KO: 2,
        DES: 8,
        SUB: 11,
        img: `${RenatoMoikano}`,
        age: 36,
        height: 180,
        weight: 70.3,
        debut: "20.12.14",
        armSpan: 183,
    },
    {
        name: "Mauricio Ruffy",
        nickname: "One Shot",
        rang: 10,
        victory: 13,
        defeat: 2,
        draw: 0,
        country: "BR",
        isChampion: false,
        KO: 12,
        DES: 1,
        SUB: 0,
        img: `${MauricioRuffi}`,
        age: 29,
        height: 180,
        weight: 70.3,
        debut: "04.05.24",
        armSpan: 191,
    },
    {
        name: "Rafael Fiziev",
        nickname: "Ataman",
        rang: 11,
        victory: 13,
        defeat: 5,
        draw: 0,
        country: "KG",
        isChampion: false,
        KO: 8,
        DES: 4,
        SUB: 1,
        img: `${RafaelFiziev}`,
        age: 33,
        height: 173,
        weight: 70.3,
        debut: "20.04.19",
        armSpan: 182,
    },
    {
        name: "Quillan Salkilld",
        nickname: "El Loco",
        rang: 12,
        victory: 12,
        defeat: 1,
        draw: 0,
        country: "MX",
        isChampion: false,
        KO: 5,
        DES: 3,
        SUB: 4,
        img: `${QuillanSalkild}`,
        age: 26,
        height: 183,
        weight: 70.3,
        debut: "08.02.25",
        armSpan: 191,
    },
    {
        name: "Michael Chandler",
        nickname: "Iron",
        rang: 13,
        victory: 23,
        defeat: 10,
        draw: 0,
        country: "US",
        isChampion: false,
        KO: 11,
        DES: 5,
        SUB: 7,
        img: `${MichaelChandler}`,
        age: 39,
        height: 173,
        weight: 70.3,
        debut: "23.01.21",
        armSpan: 182,
    },
    {
        name: "Beneil Dariush",
        nickname: "Benny",
        rang: 14,
        victory: 23,
        defeat: 7,
        draw: 1,
        country: "IR",
        isChampion: false,
        KO: 5,
        DES: 10,
        SUB: 8,
        img: `${BeneelDariusz}`,
        age: 36,
        height: 178,
        weight: 70.3,
        debut: "15.01.14",
        armSpan: 183,
    },
    {
        name: "Fares Ziam",
        nickname: "Smile Killer",
        rang: 15,
        victory: 18,
        defeat: 4,
        draw: 3,
        country: "FR",
        isChampion: false,
        KO: 7,
        DES: 7,
        SUB: 4,
        img: `${FaresZiam}`,
        age: 29,
        height: 185,
        weight: 70.3,
        debut: "07.09.19",
        armSpan: 191,
    },
];