import type { fighterType } from "../Fighters.types";

export const lightHeavyWeight: fighterType[] = [
    {
        name: "Carlos Ulberg",
        nickname: "Black Jag",
        rang: 0,
        victory: 15,
        defeat: 1,
        draw: 0,
        country: "NZ",
        isChampion: true,
        KO: 10,
        DES: 4,
        SUB: 1,
        img: "/CarlosOlberg.webp",
        age: 35,
        height: 193,
        weight: 93.0,
        debut: "06.03.21",
        armSpan: 196,
    },
    {
        name: "Magomed Ankalaev",
        nickname: "The Big Ankh",
        rang: 1,
        victory: 21,
        defeat: 2,
        draw: 1,
        country: "RU",
        isChampion: false,
        KO: 11,
        DES: 10,
        SUB: 0,
        img: "/MagomedAnkalaev.webp",
        age: 33,
        height: 191,
        weight: 93.0,
        debut: "17.03.18",
        armSpan: 191,
    },
    {
        name: "Alex Pereira",
        nickname: "Poatan",
        rang: 2,
        victory: 13,
        defeat: 3,
        draw: 0,
        country: "BR",
        isChampion: false,
        KO: 11,
        DES: 2,
        SUB: 0,
        img: "/AlexPereira.webp",
        age: 38,
        height: 193,
        weight: 93.0,
        debut: "06.11.21",
        armSpan: 201,
    },
    {
        name: "Jiri Prochazka",
        nickname: "Denisa",
        rang: 3,
        victory: 32,
        defeat: 6,
        draw: 1,
        country: "CZ",
        isChampion: false,
        KO: 28,
        DES: 1,
        SUB: 3,
        img: "/JiriProkhazka.webp",
        age: 33,
        height: 191,
        weight: 93.0,
        debut: "11.07.20",
        armSpan: 203,
    },
    {
        name: "Jan Blachowicz",
        nickname: "Prince of Cieszyn",
        rang: 4,
        victory: 29,
        defeat: 11,
        draw: 2,
        country: "PL",
        isChampion: false,
        KO: 9,
        DES: 11,
        SUB: 9,
        img: "/JanBlachowicz.webp",
        age: 43,
        height: 188,
        weight: 93.0,
        debut: "04.10.14",
        armSpan: 198,
    },
    {
        name: "Khalil Rountree Jr.",
        nickname: "The War Horse",
        rang: 5,
        victory: 15,
        defeat: 7,
        draw: 0,
        country: "US",
        isChampion: false,
        KO: 9,
        DES: 6,
        SUB: 0,
        img: "/KhalilRountreeJr.webp",
        age: 36,
        height: 185,
        weight: 93.0,
        debut: "09.07.16",
        armSpan: 194,
    },
    {
        name: "Jamahal Hill",
        nickname: "Sweet Dreams",
        rang: 6,
        victory: 12,
        defeat: 4,
        draw: 0,
        country: "US",
        isChampion: false,
        KO: 7,
        DES: 5,
        SUB: 0,
        img: "/JamalHill.webp",
        age: 34,
        height: 193,
        weight: 93.0,
        debut: "25.01.20",
        armSpan: 201,
    },
    {
        name: "Paulo Costa",
        nickname: "The Eraser",
        rang: 7,
        victory: 16,
        defeat: 4,
        draw: 0,
        country: "BR",
        isChampion: false,
        KO: 12,
        DES: 3,
        SUB: 1,
        img: "/PauloCosta.webp",
        age: 35,
        height: 185,
        weight: 93.0,
        debut: "12.03.17",
        armSpan: 183,
    },
    {
        name: "Azamat Murzakanov",
        nickname: "The Professional",
        rang: 8,
        victory: 16,
        defeat: 1,
        draw: 0,
        country: "RU",
        isChampion: false,
        KO: 12,
        DES: 3,
        SUB: 1,
        img: "/AzamatMurzakanov.webp",
        age: 35,
        height: 178,
        weight: 93.0,
        debut: "20.11.21",
        armSpan: 182,
    },
    {
        name: "Volkan Oezdemir",
        nickname: "No Time",
        rang: 9,
        victory: 21,
        defeat: 8,
        draw: 0,
        country: "CH",
        isChampion: false,
        KO: 14,
        DES: 5,
        SUB: 2,
        img: "/VolkanOzdemir.webp",
        age: 36,
        height: 188,
        weight: 93.0,
        debut: "05.02.17",
        armSpan: 191,
    },
    {
        name: "Bogdan Guskov",
        nickname: "Czarevitch",
        rang: 10,
        victory: 18,
        defeat: 3,
        draw: 1,
        country: "UZ",
        isChampion: false,
        KO: 15,
        DES: 0,
        SUB: 3,
        img: "/BogdanGuskov.webp",
        age: 33,
        height: 191,
        weight: 93.0,
        debut: "02.09.23",
        armSpan: 193,
    },
    {
        name: "Dominick Reyes",
        nickname: "The Devastator",
        rang: 11,
        victory: 16,
        defeat: 5,
        draw: 0,
        country: "US",
        isChampion: false,
        KO: 10,
        DES: 4,
        SUB: 2,
        img: "/DominicReyes.webp",
        age: 36,
        height: 193,
        weight: 93.0,
        debut: "26.06.17",
        armSpan: 196,
    },
    {
        name: "Aleksandar Rakic",
        nickname: "Rocket",
        rang: 12,
        victory: 14,
        defeat: 6,
        draw: 0,
        country: "AT",
        isChampion: false,
        KO: 9,
        DES: 4,
        SUB: 1,
        img: "/AlexanderRakich.webp",
        age: 34,
        height: 193,
        weight: 93.0,
        debut: "02.09.17",
        armSpan: 198,
    },
    {
        name: "Nikita Krylov",
        nickname: "The Miner",
        rang: 13,
        victory: 31,
        defeat: 11,
        draw: 0,
        country: "UA",
        isChampion: false,
        KO: 13,
        DES: 2,
        SUB: 16,
        img: "/NikitaKrylov.webp",
        age: 34,
        height: 191,
        weight: 93.0,
        debut: "01.09.13",
        armSpan: 197,
    },
    {
        name: "Johnny Walker",
        nickname: null,
        rang: 14,
        victory: 22,
        defeat: 10,
        draw: 0,
        country: "BR",
        isChampion: false,
        KO: 17,
        DES: 2,
        SUB: 3,
        img: "/JohnnyWalker.webp",
        age: 34,
        height: 198,
        weight: 93.0,
        debut: "17.11.18",
        armSpan: 208,
    },
    {
        name: "Alonzo Menifield",
        nickname: "Atomic",
        rang: 15,
        victory: 17,
        defeat: 6,
        draw: 1,
        country: "US",
        isChampion: false,
        KO: 10,
        DES: 4,
        SUB: 3,
        img: "/AlonzoMenifield.webp",
        age: 38,
        height: 183,
        weight: 93.0,
        debut: "19.01.19",
        armSpan: 193,
    },
];