import type { fighterType } from "../Fighters.types";
import IlyaTopuria from "../../../../../public/IlyaTopuria.png";
import JustinGage from "../../../../../public/JustinGage.png";
import ArmanTsarukyan from "../../../../../public/ArmanTsarukyan.png";
import CharlesOliveira from "../../../../../public/CharlesOliveira.png";
import MaxHolloway from "../../../../../public/MaxHolloway.png";
import BenoitSaintDenis from "../../../../../public/BenoitSaintDenis.png";
import PaddyPimblett from "../../../../../public/PaddyPimblett.png";
import MateuszGamrot from "../../../../../public/MateuszGamrot.png";
import DanHooker from "../../../../../public/DanHooker.png";
import RenatoMoikano from "../../../../../public/RenatoMoikano.png";
import MauricioRuffi from "../../../../../public/MauricioRuffi.png";
import RafaelFiziev from "../../../../../public/RafaelFiziev.png";
import BeneelDariusz from "../../../../../public/BeneelDariusz.png";
import MichaelChandler from "../../../../../public/MichaelChandler.png";
import FaresZiam from "../../../../../public/FaresZiam.png";
import QuillanSalkild from "../../../../../public/QuillanSalkild.png";

export const lightWeight: fighterType[] = [
    {
        name: 'Илия Топурия',
        nickname: `«La Leyenda»`,
        rang: 0,
        victory: 17,
        defeat: 0,
        draw: 0,
        country: 'Испания',
        isChampion: true,
        KO: 7,
        DES: 2,
        SUB: 8,
        img: `${IlyaTopuria}`,
        age: 29,
        height: 170.18,
        weight: 70.31,
        debut: '10.10.20',
        armSpan: 175.26,
    },
    {
        name: 'Джастин Гейджи',
        nickname: `«The Highlight»`,
        rang: 1,
        victory: 27,
        defeat: 5,
        draw: 0,
        country: 'США',
        isChampion: false,
        KO: 20,
        DES: 6,
        SUB: 1,
        img: `${JustinGage}`,
        age: 37,
        height: 180.34,
        weight: 70.31,
        debut: '08.07.17',
        armSpan: 177.8,
    },
    {
        name: 'Арман Царукян',
        nickname: `«Tough Guy»`,
        rang: 2,
        victory: 23,
        defeat: 3,
        draw: 0,
        country: 'Грузия',
        isChampion: false,
        KO: 9,
        DES: 8,
        SUB: 6,
        img: `${ArmanTsarukyan}`,
        age: 29,
        height: 170.18,
        weight: 70.76,
        debut: '20.04.19',
        armSpan: 184.15,
    },
    {
        name: 'Чарльз Оливейра',
        nickname: `«Do Bronx»`,
        rang: 3,
        victory: 37,
        defeat: 11,
        draw: 0,
        country: 'Бразилия',
        isChampion: false,
        KO: 10,
        DES: 5,
        SUB: 22,
        img: `${CharlesOliveira}`,
        age: 36,
        height: 177.8,
        weight: 70.76,
        debut: '01.08.10',
        armSpan: 187.96,
    },
    {
        name: 'Макс Холлоуэй',
        nickname: `«Blessed»`,
        rang: 4,
        victory: 27,
        defeat: 9,
        draw: 0,
        country: 'США',
        isChampion: false,
        KO: 12,
        DES: 13,
        SUB: 2,
        img: `${MaxHolloway}`,
        age: 34,
        height: 180.34,
        weight: 70.31,
        debut: '04.02.12',
        armSpan: 175.26,
    },
    {
        name: 'Бенуа Сэн-Дени',
        nickname: `«God of War»`,
        rang: 5,
        victory: 17,
        defeat: 3,
        draw: 0,
        country: 'Франция',
        isChampion: false,
        KO: 15,
        DES: 15,
        SUB: 6,
        img: `${BenoitSaintDenis}`,
        age: 30,
        height: 180.34,
        weight: 77.52,
        debut: '30.10.21',
        armSpan: 185.42,
    },
    {
        name: 'Пэдди Пимблетт',
        nickname: `«The Baddy»`,
        rang: 6,
        victory: 23,
        defeat: 4,
        draw: 0,
        country: 'Англия',
        isChampion: false,
        KO: 7,
        DES: 6,
        SUB: 10,
        img: `${PaddyPimblett}`,
        age: 31,
        height: 177.8,
        weight: 70.08,
        debut: '04.09.21',
        armSpan: 185.42,
    },
    {
        name: 'Матеуш Гамрот',
        nickname: `«Gamer»`,
        rang: 7,
        victory: 26,
        defeat: 4,
        draw: 0,
        country: 'Польша',
        isChampion: false,
        KO: 8,
        DES: 12,
        SUB: 6,
        img: `${MateuszGamrot}`,
        age: 35,
        height: 177.8,
        weight: 70.76,
        debut: '17.10.20',
        armSpan: 179.07,
    },
    {
        name: 'Дэн Хукер',
        nickname: `«The Hangman»`,
        rang: 8,
        victory: 24,
        defeat: 14,
        draw: 0,
        country: 'Новая Зеландия',
        isChampion: false,
        KO: 11,
        DES: 6,
        SUB: 7,
        img: `${DanHooker}`,
        age: 36,
        height: 182.88,
        weight: 76.97,
        debut: '28.06.14',
        armSpan: 190.5,
    },
    {
        name: 'Ренато Мойкано',
        nickname: `«Money Moicano»`,
        rang: 9,
        victory: 21,
        defeat: 7,
        draw: 1,
        country: 'Бразилия',
        isChampion: false,
        KO: 2,
        DES: 8,
        SUB: 11,
        img: `${RenatoMoikano}`,
        age: 36,
        height: 180.34,
        weight: 70.76,
        debut: '20.12.14',
        armSpan: 182.88,
    },
    {
        name: 'Маурисио Руффи',
        nickname: `«One Shot»`,
        rang: 10,
        victory: 13,
        defeat: 2,
        draw: 0,
        country: 'Бразилия',
        isChampion: false,
        KO: 12,
        DES: 1,
        SUB: 0,
        img: `${MauricioRuffi}`,
        age: 29,
        height: 180.34,
        weight: 76.97,
        debut: '04.05.24',
        armSpan: 190.5,
    },
    {
        name: 'Рафаэль Физиев',
        nickname: `«Ataman»`,
        rang: 11,
        victory: 13,
        defeat: 5,
        draw: 0,
        country: 'Киргизия',
        isChampion: false,
        KO: 8,
        DES: 4,
        SUB: 1,
        img: `${RafaelFiziev}`,
        age: 33,
        height: 172.72,
        weight: 77.11,
        debut: '20.04.19',
        armSpan: 181.61,
    },
    {
        name: 'Куиллан Салкиллд',
        nickname: `«El Loco»`,
        rang: 12,
        victory: 12,
        defeat: 1,
        draw: 0,
        country: 'Мексика',
        isChampion: false,
        KO: 5,
        DES: 3,
        SUB: 4,
        img: `${QuillanSalkild}`,
        age: 26,
        height: 182.88,
        weight: 77.79,
        debut: '08.02.25',
        armSpan: 190.5,
    },
    {
        name: 'Майкл Чендлер',
        nickname: `«Iron»`,
        rang: 13,
        victory: 23,
        defeat: 10,
        draw: 0,
        country: 'США',
        isChampion: false,
        KO: 11,
        DES: 5,
        SUB: 7,
        img: `${MichaelChandler}`,
        age: 39,
        height: 172.72,
        weight: 70.76,
        debut: '23.01.21',
        armSpan: 181.61,
    },
    {
        name: 'Бенэил Дариуш',
        nickname: `«Benny»`,
        rang: 14,
        victory: 23,
        defeat: 7,
        draw: 1,
        country: 'Иран',
        isChampion: false,
        KO: 5,
        DES: 10,
        SUB: 8,
        img: `${BeneelDariusz}`,
        age: 36,
        height: 177.8,
        weight: 71.3,
        debut: '15.01.14',
        armSpan: 182.88,
    },
    {
        name: 'Фарес Зиам',
        nickname: `«Smile Killer»`,
        rang: 15,
        victory: 18,
        defeat: 4,
        draw: 3,
        country: 'Франция',
        isChampion: false,
        KO: 7,
        DES: 7,
        SUB: 4,
        img: `${FaresZiam}`,
        age: 29,
        height: 185.42,
        weight: 70.76,
        debut: '07.09.19',
        armSpan: 190.5,
    },

];