import type { fighterType } from "../Fighters.types";
import CarlosOlberg from "../../../../../public/CarlosOlberg.png";
import MagomedAnkalaev from "../../../../../public/MagomedAnkalaev.png";
import AlexPereira from "../../../../../public/AlexPereira.png";
import JiriProkhazka from "../../../../../public/JiriProkhazka.png";
import JanBlachowicz from "../../../../../public/JanBlachowicz.png";
import KhalilRountreeJr from "../../../../../public/KhalilRountreeJr.png";
import JamalHill from "../../../../../public/JamalHill.png";
import PauloCosta from "../../../../../public/PauloCosta.png";
import AzamatMurzakanov from "../../../../../public/AzamatMurzakanov.png";
import VolkanOzdemir from "../../../../../public/VolkanOzdemir.png";
import BogdanGuskov from "../../../../../public/BogdanGuskov.jpg";
import DominicReyes from "../../../../../public/DominicReyes.png";
import AlexanderRakich from "../../../../../public/AlexanderRakich.jpg";
import NikitaKrylov from "../../../../../public/NikitaKrylov.jpg";
import JohnnyWalker from "../../../../../public/JohnnyWalker.png";
import AlonzoMenifield from "../../../../../public/AlonzoMenifield.png";

export const lightHeavyWeight: fighterType[] = [
    {
        name: 'Карлос Ульберг',
        nickname: `«Black Jag»`,
        rang: 0,
        victory: 15,
        defeat: 1,
        draw: 0,
        country: 'Новая Зеландия',
        isChampion: true,
        KO: 10,
        DES: 4,
        SUB: 1,
        img: `${CarlosOlberg}`,
        age: 35,
        height: 193.04,
        weight: 92.99,
        debut: '06.03.21',
        armSpan: 195.58,
    },
    {
        name: 'Магомед Анкалаев',
        nickname: `«The Big Ankh»`,
        rang: 1,
        victory: 21,
        defeat: 2,
        draw: 1,
        country: 'Россия',
        isChampion: false,
        KO: 11,
        DES: 10,
        SUB: 0,
        img: `${MagomedAnkalaev}`,
        age: 33,
        height: 190.5,
        weight: 92.76,
        debut: '17.03.18',
        armSpan: 190.5,
    },
    {
        name: 'Алекс Перейра',
        nickname: `«Poatan»`,
        rang: 2,
        victory: 13,
        defeat: 3,
        draw: 0,
        country: 'Бразилия',
        isChampion: false,
        KO: 11,
        DES: 2,
        SUB: 0,
        img: `${AlexPereira}`,
        age: 38,
        height: 193.04,
        weight: 92.76,
        debut: '06.11.21',
        armSpan: 200.66,
    },
    {
        name: 'Иржи Прохазка',
        nickname: `«Denisa»`,
        rang: 3,
        victory: 32,
        defeat: 6,
        draw: 1,
        country: 'Чехия',
        isChampion: false,
        KO: 28,
        DES: 1,
        SUB: 3,
        img: `${JiriProkhazka}`,
        age: 33,
        height: 190.5,
        weight: 93.44,
        debut: '11.07.20',
        armSpan: 203.2,
    },
    {
        name: 'Ян Блахович',
        nickname: `«Denisa»`,
        rang: 4,
        victory: 29,
        defeat: 11,
        draw: 2,
        country: 'Польша',
        isChampion: false,
        KO: 9,
        DES: 11,
        SUB: 9,
        img: `${JanBlachowicz}`,
        age: 43,
        height: 187.96,
        weight: 93.44,
        debut: '04.10.14',
        armSpan: 198.12,
    },
    {
        name: 'Халил Раунтри Мл.',
        nickname: `«The War Horse»`,
        rang: 5,
        victory: 15,
        defeat: 7,
        draw: 0,
        country: 'США',
        isChampion: false,
        KO: 9,
        DES: 6,
        SUB: 0,
        img: `${KhalilRountreeJr}`,
        age: 36,
        height: 185.42,
        weight: 92.99,
        debut: '09.07.16',
        armSpan: 194.31,
    },
    {
        name: 'Джамал Хилл',
        nickname: `«Sweet Dreams»`,
        rang: 6,
        victory: 12,
        defeat: 4,
        draw: 0,
        country: 'США',
        isChampion: false,
        KO: 7,
        DES: 5,
        SUB: 0,
        img: `${JamalHill}`,
        age: 34,
        height: 193.04,
        weight: 93.44,
        debut: '25.01.20',
        armSpan: 200.66,
    },
    {
        name: 'Пауло Коста',
        nickname: `«The Eraser»`,
        rang: 7,
        victory: 16,
        defeat: 4,
        draw: 0,
        country: 'Бразилия',
        isChampion: false,
        KO: 12,
        DES: 3,
        SUB: 1,
        img: `${PauloCosta}`,
        age: 35,
        height: 185.42,
        weight: 83.91,
        debut: '12.03.17',
        armSpan: 182.88,
    },
    {
        name: 'Азамат Мурзаканов',
        nickname: `«The Professional»`,
        rang: 8,
        victory: 16,
        defeat: 1,
        draw: 0,
        country: 'Россия',
        isChampion: false,
        KO: 12,
        DES: 3,
        SUB: 1,
        img: `${AzamatMurzakanov}`,
        age: 35,
        height: 177.8,
        weight: 93.21,
        debut: '20.11.21',
        armSpan: 181.61,
    },
    {
        name: 'Волкан Оздемир',
        nickname: `«No Time»`,
        rang: 9,
        victory: 21,
        defeat: 8,
        draw: 0,
        country: 'Швейцария',
        isChampion: false,
        KO: 14,
        DES: 5,
        SUB: 2,
        img: `${VolkanOzdemir}`,
        age: 36,
        height: 187.96,
        weight: 93.44,
        debut: '05.02.17',
        armSpan: 190.5,
    },
    {
        name: 'Богдан Гуськов',
        nickname: `«Czarevitch»`,
        rang: 10,
        victory: 18,
        defeat: 3,
        draw: 1,
        country: 'Узбекистан',
        isChampion: false,
        KO: 15,
        DES: 0,
        SUB: 3,
        img: `${BogdanGuskov}`,
        age: 33,
        height: 190.5,
        weight: 92.99,
        debut: '02.09.23',
        armSpan: 193.04,
    },
    {
        name: 'Доминик Рейес',
        nickname: `«The Devastator»`,
        rang: 11,
        victory: 16,
        defeat: 5,
        draw: 0,
        country: 'США',
        isChampion: false,
        KO: 10,
        DES: 4,
        SUB: 2,
        img: `${DominicReyes}`,
        age: 36,
        height: 193.04,
        weight: 93.44,
        debut: '26.06.17',
        armSpan: 195.58,
    },
    {
        name: 'Александр Ракич',
        nickname: `«Rocket»`,
        rang: 12,
        victory: 14,
        defeat: 6,
        draw: 0,
        country: 'Австрия',
        isChampion: false,
        KO: 9,
        DES: 4,
        SUB: 1,
        img: `${AlexanderRakich}`,
        age: 34,
        height: 193.04,
        weight: 92.99,
        debut: '02.09.17',
        armSpan: 198.12,
    },
    {
        name: 'Никита Крылов',
        nickname: `«The Miner»`,
        rang: 13,
        victory: 31,
        defeat: 11,
        draw: 0,
        country: 'Украина',
        isChampion: false,
        KO: 13,
        DES: 2,
        SUB: 16,
        img: `${NikitaKrylov}`,
        age: 34,
        height: 190.5,
        weight: 93.21,
        debut: '01.09.13',
        armSpan: 196.85,
    },
    {
        name: 'Джонни Уокер',
        nickname: null,
        rang: 14,
        victory: 22,
        defeat: 10,
        draw: 0,
        country: 'Бразилия',
        isChampion: false,
        KO: 13,
        DES: 2,
        SUB: 16,
        img: `${JohnnyWalker}`,
        age: 34,
        height: 198.12,
        weight: 93.44,
        debut: '17.11.18',
        armSpan: 208.28,
    },
    {
        name: 'Алонзо Менифилд',
        nickname: `«Atomic»`,
        rang: 15,
        victory: 17,
        defeat: 6,
        draw: 1,
        country: 'США',
        isChampion: false,
        KO: 10,
        DES: 4,
        SUB: 3,
        img: `${AlonzoMenifield}`,
        age: 38,
        height: 182.88,
        weight: 93.44,
        debut: '19.01.19',
        armSpan: 193.04,
    },
];