import type { fighterType } from "../Fighters.types";
import SeanStrickland from "../../../../../public/SeanStrickland.png";
import KhamzatChimaev from "../../../../../public/KhamzatChimaev.png";
import DrikusDuPlessis from "../../../../../public/DrikusDuPlessis.png";
import NassurdinImavov from "../../../../../public/NassurdinImavov.png";
import BrendanAllen from "../../../../../public/BrendanAllen.png";
import AnthonyHernandez from "../../../../../public/AnthonyHernandez.png";
import CayoBorrallo from "../../../../../public/CayoBorrallo.png";
import JoePifer from "../../../../../public/JoePifer.png";
import RainierdeRidder from "../../../../../public/RainierdeRidder.png";
import IsraelAdesanya from "../../../../../public/IsraelAdesanya.png";
import RobertWhittaker from "../../../../../public/RobertWhittaker.png";
import JaredCannonier from "../../../../../public/JaredCannonier.png";
import GregoryRodriguez from "../../../../../public/GregoryRodriguez.jpg";
import ChristianLeroyDuncan from "../../../../../public/ChristianLeroyDuncan.jpg";
import PauloCosta from "../../../../../public/PauloCosta.png";
import RomanDolidze from "../../../../../public/RomanDolidze.jpg";

export const middleWeight: fighterType[] = [
    {
        name: 'Шон Стрикланд',
        nickname: `«Tarzan»`,
        rang: 0,
        victory: 31,
        defeat: 7,
        draw: 0,
        country: 'США',
        isChampion: true,
        KO: 12,
        DES: 15,
        SUB: 4,
        img: `${SeanStrickland}`,
        age: 35,
        height: 185.42,
        weight: 83.91,
        debut: '15.03.14',
        armSpan: 193.04,
    },
    {
        name: 'Хамзат Чимаев',
        nickname: `«Borz»`,
        rang: 1,
        victory: 15,
        defeat: 1,
        draw: 0,
        country: 'ОАЭ',
        isChampion: false,
        KO: 6,
        DES: 3,
        SUB: 6,
        img: `${KhamzatChimaev}`,
        age: 32,
        height: 187.96,
        weight: 83.01,
        debut: '15.07.20',
        armSpan: 190.5,
    },
    {
        name: 'Дрикус Дю Плесси',
        nickname: `«Stillknocks»`,
        rang: 2,
        victory: 23,
        defeat: 3,
        draw: 0,
        country: 'ЮАР',
        isChampion: false,
        KO: 9,
        DES: 3,
        SUB: 11,
        img: `${DrikusDuPlessis}`,
        age: 32,
        height: 185.42,
        weight: 83.91,
        debut: '10.10.20',
        armSpan: 193.04,
    },
    {
        name: 'Нассурдин Имавов',
        nickname: `«The Russian Sniper»`,
        rang: 3,
        victory: 17,
        defeat: 4,
        draw: 0,
        country: 'Россия',
        isChampion: false,
        KO: 7,
        DES: 6,
        SUB: 4,
        img: `${NassurdinImavov}`,
        age: 30,
        height: 190.5,
        weight: 83.91,
        debut: '03.10.20',
        armSpan: 190.5,
    },
    {
        name: 'Кайо Борральо',
        nickname: `«The Natural»`,
        rang: 4,
        victory: 18,
        defeat: 2,
        draw: 0,
        country: 'Бразилия',
        isChampion: false,
        KO: 5,
        DES: 9,
        SUB: 4,
        img: `${CayoBorrallo}`,
        age: 33,
        height: 186.69,
        weight: 83.91,
        debut: '16.04.22',
        armSpan: 190.5,
    },
    {
        name: 'Брендан Аллен',
        nickname: `«All In»`,
        rang: 5,
        victory: 26,
        defeat: 7,
        draw: 0,
        country: 'США',
        isChampion: false,
        KO: 6,
        DES: 6,
        SUB: 14,
        img: `${BrendanAllen}`,
        age: 30,
        height: 187.96,
        weight: 84.37,
        debut: '18.10.19',
        armSpan: 190.5,
    },
    {
        name: 'Джо Пайфер',
        nickname: `«Bodybagz»`,
        rang: 6,
        victory: 16,
        defeat: 3,
        draw: 0,
        country: 'США',
        isChampion: false,
        KO: 10,
        DES: 2,
        SUB: 4,
        img: `${JoePifer}`,
        age: 29,
        height: 187.96,
        weight: 84.37,
        debut: '17.09.22',
        armSpan: 190.5,
    },
    {
        name: 'Энтони Хернандез',
        nickname: `«Fluffy»`,
        rang: 7,
        victory: 15,
        defeat: 3,
        draw: 0,
        country: 'США',
        isChampion: false,
        KO: 3,
        DES: 3,
        SUB: 9,
        img: `${AnthonyHernandez}`,
        age: 32,
        height: 182.88,
        weight: 84.37,
        debut: '02.02.19',
        armSpan: 190.5,
    },
    {
        name: 'Ренье де Риддер',
        nickname: `«The Dutch Knight»`,
        rang: 8,
        victory: 21,
        defeat: 4,
        draw: 0,
        country: 'Нидерланды',
        isChampion: false,
        KO: 5,
        DES: 3,
        SUB: 13,
        img: `${RainierdeRidder}`,
        age: 35,
        height: 193.04,
        weight: 84.37,
        debut: '09.11.24',
        armSpan: 198.12,
    },
    {
        name: 'Исраэль Адесанья',
        nickname: `«The Last Stylebender»`,
        rang: 9,
        victory: 24,
        defeat: 6,
        draw: 0,
        country: 'Нигерия',
        isChampion: false,
        KO: 16,
        DES: 8,
        SUB: 0,
        img: `${IsraelAdesanya}`,
        age: 36,
        height: 193.04,
        weight: 83.91,
        debut: '11.02.18',
        armSpan: 203.2,
    },
    {
        name: 'Роберт Уиттакер',
        nickname: `«The Reaper»`,
        rang: 10,
        victory: 27,
        defeat: 9,
        draw: 0,
        country: 'Австралия',
        isChampion: false,
        KO: 11,
        DES: 11,
        SUB: 5,
        img: `${RobertWhittaker}`,
        age: 35,
        height: 182.88,
        weight: 84.14,
        debut: '16.12.12',
        armSpan: 186.69,
    },
    {
        name: 'Джаред Каннонир',
        nickname: `«Tha Killa Gorilla»`,
        rang: 11,
        victory: 18,
        defeat: 9,
        draw: 0,
        country: 'США',
        isChampion: false,
        KO: 11,
        DES: 5,
        SUB: 2,
        img: `${JaredCannonier}`,
        age: 42,
        height: 180.34,
        weight: 84.37,
        debut: '03.01.15',
        armSpan: 196.85,
    },
    {
        name: 'Грегори Родригес',
        nickname: `«Robocop»`,
        rang: 12,
        victory: 19,
        defeat: 6,
        draw: 0,
        country: 'Бразилия',
        isChampion: false,
        KO: 12,
        DES: 4,
        SUB: 3,
        img: `${GregoryRodriguez}`,
        age: 34,
        height: 190.5,
        weight: 84.28,
        debut: '05.06.21',
        armSpan: 190.5,
    },
    {
        name: 'Кристиан Лерой Данкан',
        nickname: `«CLD»`,
        rang: 13,
        victory: 14,
        defeat: 2,
        draw: 0,
        country: 'Великобритания',
        isChampion: false,
        KO: 10,
        DES: 3,
        SUB: 1,
        img: `${ChristianLeroyDuncan}`,
        age: 30,
        height: 187.96,
        weight: 83.91,
        debut: '18.03.23',
        armSpan: 200.66,
    },
    {
        name: 'Пауло Коста',
        nickname: `«The Eraser»`,
        rang: 14,
        victory: 16,
        defeat: 4,
        draw: 0,
        country: 'Бразилия',
        isChampion: false,
        KO: 12,
        DES: 3,
        SUB: 1,
        img: `${PauloCosta}`,
        age: 35,
        height: 185.42,
        weight: 83.91,
        debut: '12.03.17',
        armSpan: 182.88,
    },
    {
        name: 'Роман Долидзе',
        nickname: `«Caucasian»`,
        rang: 15,
        victory: 15,
        defeat: 5,
        draw: 0,
        country: 'Грузия',
        isChampion: false,
        KO: 8,
        DES: 4,
        SUB: 3,
        img: `${RomanDolidze}`,
        age: 37,
        height: 187.96,
        weight: 84.14,
        debut: '18.07.20',
        armSpan: 193.04,
    },
];