import type { fighterType } from "../Fighters.types";
import SeanStrickland from "../../../../../public/SeanStrickland.png";
import KhamzatChimaev from "../../../../../public/KhamzatChimaev.png";
import DrikusDuPlessis from "../../../../../public/DrikusDuPlessis.png";
import NassurdinImavov from "../../../../../public/NassurdinImavov.png";
import BrendanAllen from "../../../../../public/BrendanAllen.png";
import AnthonyHernandez from "../../../../../public/AnthonyHernandez.png";
import CayoBorrallo from "../../../../../public/CayoBorrallo.png";
import JoePifer from "../../../../../public/JoePifer.png";
import RainierdeRidder from "../../../../../public/RainierdeRidder.png";
import IsraelAdesanya from "../../../../../public/IsraelAdesanya.png";
import RobertWhittaker from "../../../../../public/RobertWhittaker.png";
import JaredCannonier from "../../../../../public/JaredCannonier.png";
import GregoryRodriguez from "../../../../../public/GregoryRodriguez.jpg";
import ChristianLeroyDuncan from "../../../../../public/ChristianLeroyDuncan.jpg";
import PauloCosta from "../../../../../public/PauloCosta.png";
import RomanDolidze from "../../../../../public/RomanDolidze.jpg";

export const middleWeight: fighterType[] = [
  {
    name: "Sean Strickland",
    nickname: "Tarzan",
    rang: 0,
    victory: 31,
    defeat: 7,
    draw: 0,
    country: "US",
    isChampion: true,
    KO: 12,
    DES: 15,
    SUB: 4,
    img: `${SeanStrickland}`,
    age: 35,
    height: 185,
    weight: 83.9,
    debut: "15.03.14",
    armSpan: 193,
  },
  {
    name: "Khamzat Chimaev",
    nickname: "Borz",
    rang: 1,
    victory: 15,
    defeat: 1,
    draw: 0,
    country: "AE",
    isChampion: false,
    KO: 6,
    DES: 3,
    SUB: 6,
    img: `${KhamzatChimaev}`,
    age: 32,
    height: 188,
    weight: 83.9,
    debut: "15.07.20",
    armSpan: 191,
  },
  {
    name: "Dricus Du Plessis",
    nickname: "Stillknocks",
    rang: 2,
    victory: 23,
    defeat: 3,
    draw: 0,
    country: "ZA",
    isChampion: false,
    KO: 9,
    DES: 3,
    SUB: 11,
    img: `${DrikusDuPlessis}`,
    age: 32,
    height: 185,
    weight: 83.9,
    debut: "10.10.20",
    armSpan: 193,
  },
  {
    name: "Nassourdine Imavov",
    nickname: "The Russian Sniper",
    rang: 3,
    victory: 17,
    defeat: 4,
    draw: 0,
    country: "RU",
    isChampion: false,
    KO: 7,
    DES: 6,
    SUB: 4,
    img: `${NassurdinImavov}`,
    age: 30,
    height: 191,
    weight: 83.9,
    debut: "03.10.20",
    armSpan: 191,
  },
  {
    name: "Caio Borralho",
    nickname: "The Natural",
    rang: 4,
    victory: 18,
    defeat: 2,
    draw: 0,
    country: "BR",
    isChampion: false,
    KO: 5,
    DES: 9,
    SUB: 4,
    img: `${CayoBorrallo}`,
    age: 33,
    height: 187,
    weight: 83.9,
    debut: "16.04.22",
    armSpan: 191,
  },
  {
    name: "Brendan Allen",
    nickname: "All In",
    rang: 5,
    victory: 26,
    defeat: 7,
    draw: 0,
    country: "US",
    isChampion: false,
    KO: 6,
    DES: 6,
    SUB: 14,
    img: `${BrendanAllen}`,
    age: 30,
    height: 188,
    weight: 83.9,
    debut: "18.10.19",
    armSpan: 191,
  },
  {
    name: "Joe Pyfer",
    nickname: "Bodybagz",
    rang: 6,
    victory: 16,
    defeat: 3,
    draw: 0,
    country: "US",
    isChampion: false,
    KO: 10,
    DES: 2,
    SUB: 4,
    img: `${JoePifer}`,
    age: 29,
    height: 188,
    weight: 83.9,
    debut: "17.09.22",
    armSpan: 191,
  },
  {
    name: "Anthony Hernandez",
    nickname: "Fluffy",
    rang: 7,
    victory: 15,
    defeat: 3,
    draw: 0,
    country: "US",
    isChampion: false,
    KO: 3,
    DES: 3,
    SUB: 9,
    img: `${AnthonyHernandez}`,
    age: 32,
    height: 183,
    weight: 83.9,
    debut: "02.02.19",
    armSpan: 191,
  },
  {
    name: "Reinier de Ridder",
    nickname: "The Dutch Knight",
    rang: 8,
    victory: 21,
    defeat: 4,
    draw: 0,
    country: "NL",
    isChampion: false,
    KO: 5,
    DES: 3,
    SUB: 13,
    img: `${RainierdeRidder}`,
    age: 35,
    height: 193,
    weight: 83.9,
    debut: "09.11.24",
    armSpan: 198,
  },
  {
    name: "Israel Adesanya",
    nickname: "The Last Stylebender",
    rang: 9,
    victory: 24,
    defeat: 6,
    draw: 0,
    country: "NG",
    isChampion: false,
    KO: 16,
    DES: 8,
    SUB: 0,
    img: `${IsraelAdesanya}`,
    age: 36,
    height: 193,
    weight: 83.9,
    debut: "11.02.18",
    armSpan: 203,
  },
  {
    name: "Robert Whittaker",
    nickname: "The Reaper",
    rang: 10,
    victory: 27,
    defeat: 9,
    draw: 0,
    country: "AU",
    isChampion: false,
    KO: 11,
    DES: 11,
    SUB: 5,
    img: `${RobertWhittaker}`,
    age: 35,
    height: 183,
    weight: 83.9,
    debut: "16.12.12",
    armSpan: 187,
  },
  {
    name: "Jared Cannonier",
    nickname: "Tha Killa Gorilla",
    rang: 11,
    victory: 18,
    defeat: 9,
    draw: 0,
    country: "US",
    isChampion: false,
    KO: 11,
    DES: 5,
    SUB: 2,
    img: `${JaredCannonier}`,
    age: 42,
    height: 180,
    weight: 83.9,
    debut: "03.01.15",
    armSpan: 197,
  },
  {
    name: "Gregory Rodrigues",
    nickname: "Robocop",
    rang: 12,
    victory: 19,
    defeat: 6,
    draw: 0,
    country: "BR",
    isChampion: false,
    KO: 12,
    DES: 4,
    SUB: 3,
    img: `${GregoryRodriguez}`,
    age: 34,
    height: 191,
    weight: 83.9,
    debut: "05.06.21",
    armSpan: 191,
  },
  {
    name: "Christian Leroy Duncan",
    nickname: "CLD",
    rang: 13,
    victory: 14,
    defeat: 2,
    draw: 0,
    country: "GB",
    isChampion: false,
    KO: 10,
    DES: 3,
    SUB: 1,
    img: `${ChristianLeroyDuncan}`,
    age: 30,
    height: 188,
    weight: 83.9,
    debut: "18.03.23",
    armSpan: 201,
  },
  {
    name: "Paulo Costa",
    nickname: "The Eraser",
    rang: 14,
    victory: 16,
    defeat: 4,
    draw: 0,
    country: "BR",
    isChampion: false,
    KO: 12,
    DES: 3,
    SUB: 1,
    img: `${PauloCosta}`,
    age: 35,
    height: 185,
    weight: 83.9,
    debut: "12.03.17",
    armSpan: 183,
  },
  {
    name: "Roman Dolidze",
    nickname: "Caucasian",
    rang: 15,
    victory: 15,
    defeat: 5,
    draw: 0,
    country: "GE",
    isChampion: false,
    KO: 8,
    DES: 4,
    SUB: 3,
    img: `${RomanDolidze}`,
    age: 37,
    height: 188,
    weight: 83.9,
    debut: "18.07.20",
    armSpan: 193,
  },
];