import type { fighterType } from "../Fighters.types";
import IslamMakhachev from "../../../../../public/IslamMakhachev.png";
import IanMachadoGary from "../../../../../public/IanMachadoGary.png";
import CarlosPrates from "../../../../../public/CarlosPrates.png";
import MichaelMorales from "../../../../../public/MichaelMorales.png";
import JackDellaMaddalena from "../../../../../public/JackDellaMaddalena.png";
import BelalMuhammad from "../../../../../public/BelalMuhammad.png";
import SeanBrady from "../../../../../public/SeanBrady.png";
import LeonEdwards from "../../../../../public/LeonEdwards.png";
import KamaruUsman from "../../../../../public/KamaruUsman.png";
import JoaquinBuckley from "../../../../../public/JoaquinBuckley.png";
import GabrielBonfim from "../../../../../public/GabrielBonfim.png";
import MikeMalott from "../../../../../public/MikeMalott.png";
import UrosMedich from "../../../../../public/UrosMedich.png";
import MichaelPage from "../../../../../public/MichaelPage.png";
import YaroslavAmosov from "../../../../../public/YaroslavAmosov.png";
import DanielRodriguez from "../../../../../public/DanielRodriguez.png";

export const welterWeight: fighterType[] = [
    {
        name: 'Ислам Махачев',
        nickname: ``,
        rang: 0,
        victory: 28,
        defeat: 1,
        draw: 0,
        country: 'Россия',
        isChampion: true,
        KO: 5,
        DES: 10,
        SUB: 13,
        img: `${IslamMakhachev}`,
        age: 34,
        height: 177.8,
        weight: 70.08,
        debut: '23.05.15',
        armSpan: 179.07,
    },
    {
        name: 'Иэн Мачадо Гэрри',
        nickname: `«The Future»`,
        rang: 1,
        victory: 17,
        defeat: 1,
        draw: 0,
        country: 'Ирландия',
        isChampion: false,
        KO: 7,
        DES: 9,
        SUB: 1,
        img: `${IanMachadoGary}`,
        age: 28,
        height: 190.5,
        weight: 77.11,
        debut: '06.11.21',
        armSpan: 189.23,
    },
    {
        name: 'Карлос Пратес',
        nickname: `«The Nightmare»`,
        rang: 2,
        victory: 24,
        defeat: 7,
        draw: 0,
        country: 'Бразилия',
        isChampion: false,
        KO: 19,
        DES: 2,
        SUB: 3,
        img: `${CarlosPrates}`,
        age: 32,
        height: 185.42,
        weight: 76.93,
        debut: '10.02.24',
        armSpan: 198.12,
    },
    {
        name: 'Майкл Моралес',
        nickname: null,
        rang: 3,
        victory: 19,
        defeat: 0,
        draw: 0,
        country: 'Эквадор',
        isChampion: false,
        KO: 14,
        DES: 4,
        SUB: 1,
        img: `${MichaelMorales}`,
        age: 26,
        height: 182.88,
        weight: 77.38,
        debut: '22.01.22',
        armSpan: 200.66,
    },
    {
        name: 'Джек Делла Маддалена',
        nickname: `«JDM»`,
        rang: 4,
        victory: 18,
        defeat: 4,
        draw: 0,
        country: 'Австралия',
        isChampion: false,
        KO: 12,
        DES: 4,
        SUB: 2,
        img: `${JackDellaMaddalena}`,
        age: 29,
        height: 180.34,
        weight: 77.02,
        debut: '22.01.22',
        armSpan: 185.42,
    },
    {
        name: 'Белал Мухаммад',
        nickname: `«Remember The Name»`,
        rang: 5,
        victory: 24,
        defeat: 5,
        draw: 0,
        country: 'США',
        isChampion: false,
        KO: 5,
        DES: 18,
        SUB: 1,
        img: `${BelalMuhammad}`,
        age: 37,
        height: 180.34,
        weight: 77.56,
        debut: '07.07.16',
        armSpan: 182.88,
    },
    {
        name: 'Шон Брэди',
        nickname: `«The Quiet Storm»`,
        rang: 6,
        victory: 19,
        defeat: 2,
        draw: 0,
        country: 'США',
        isChampion: false,
        KO: 3,
        DES: 10,
        SUB: 6,
        img: `${SeanBrady}`,
        age: 33,
        height: 177.8,
        weight: 76.84,
        debut: '18.10.19',
        armSpan: 182.88,
    },
    {
        name: 'Леон Эдвардс',
        nickname: `«Rocky»`,
        rang: 7,
        victory: 22,
        defeat: 6,
        draw: 0,
        country: 'Ямайка',
        isChampion: false,
        KO: 7,
        DES: 12,
        SUB: 3,
        img: `${LeonEdwards}`,
        age: 34,
        height: 182.88,
        weight: 77.11,
        debut: '09.11.14',
        armSpan: 187.96,
    },
    {
        name: 'Камару Усман',
        nickname: `«Nigerian Nightmare»`,
        rang: 8,
        victory: 21,
        defeat: 4,
        draw: 0,
        country: 'Нигерия',
        isChampion: false,
        KO: 9,
        DES: 11,
        SUB: 1,
        img: `${KamaruUsman}`,
        age: 38,
        height: 182.88,
        weight: 77.56,
        debut: '12.07.15',
        armSpan: 193.04,
    },
    {
        name: 'Хоакин Бакли',
        nickname: `«New Mansa»`,
        rang: 9,
        victory: 21,
        defeat: 8,
        draw: 0,
        country: 'США',
        isChampion: false,
        KO: 15,
        DES: 6,
        SUB: 0,
        img: `${JoaquinBuckley}`,
        age: 32,
        height: 177.8,
        weight: 77.56,
        debut: '08.08.20',
        armSpan: 193.04,
    },
    {
        name: 'Габриэль Бонфим',
        nickname: `«Marretinha»`,
        rang: 10,
        victory: 19,
        defeat: 1,
        draw: 0,
        country: 'Бразилия',
        isChampion: false,
        KO: 4,
        DES: 2,
        SUB: 13,
        img: `${GabrielBonfim}`,
        age: 28,
        height: 185.42,
        weight: 77.34,
        debut: '21.01.23',
        armSpan: 184.15,
    },
    {
        name: 'Майк Мэлотт',
        nickname: `«Proper»`,
        rang: 11,
        victory: 14,
        defeat: 2,
        draw: 1,
        country: 'США',
        isChampion: false,
        KO: 6,
        DES: 2,
        SUB: 6,
        img: `${MikeMalott}`,
        age: 34,
        height: 185.42,
        weight: 77.56,
        debut: '09.04.22',
        armSpan: 185.42,
    },
    {
        name: 'Урош Медич',
        nickname: `«The Doctor»`,
        rang: 12,
        victory: 13,
        defeat: 3,
        draw: 0,
        country: 'Сербия',
        isChampion: false,
        KO: 11,
        DES: 0,
        SUB: 2,
        img: `${UrosMedich}`,
        age: 33,
        height: 185.42,
        weight: 77.56,
        debut: '06.03.21',
        armSpan: 180.34,
    },
    {
        name: 'Майкл Пэйдж',
        nickname: `«Venom»`,
        rang: 13,
        victory: 25,
        defeat: 3,
        draw: 0,
        country: 'Великобритания',
        isChampion: false,
        KO: 13,
        DES: 9,
        SUB: 3,
        img: `${MichaelPage}`,
        age: 39,
        height: 190.5,
        weight: 83.91,
        debut: '09.03.24',
        armSpan: 200.66,
    },
    {
        name: 'Ярослав Амосов',
        nickname: `«Dynamo»`,
        rang: 14,
        victory: 29,
        defeat: 1,
        draw: 0,
        country: 'Украина',
        isChampion: false,
        KO: 9,
        DES: 8,
        SUB: 12,
        img: `${YaroslavAmosov}`,
        age: 32,
        height: 182.88,
        weight: 77.11,
        debut: '13.12.25',
        armSpan: 190.5,
    },
    {
        name: 'Дэниел Родригез',
        nickname: `«D-Rod»`,
        rang: 15,
        victory: 20,
        defeat: 5,
        draw: 0,
        country: 'США',
        isChampion: false,
        KO: 9,
        DES: 7,
        SUB: 4,
        img: `${DanielRodriguez}`,
        age: 39,
        height: 185.42,
        weight: 77.11,
        debut: '15.02.20',
        armSpan: 187.96,
    },
];