import type { fighterType } from "../Fighters.types";

export const welterWeight: fighterType[] = [
  {
    name: "Islam Makhachev",
    nickname: "",
    rang: 0,
    victory: 28,
    defeat: 1,
    draw: 0,
    country: "RU",
    isChampion: true,
    KO: 5,
    DES: 10,
    SUB: 13,
    img: "/IslamMakhachev.webp",
    age: 34,
    height: 178,
    weight: 77.1,
    debut: "23.05.15",
    armSpan: 179,
  },
  {
    name: "Ian Machado Garry",
    nickname: "The Future",
    rang: 1,
    victory: 17,
    defeat: 1,
    draw: 0,
    country: "IE",
    isChampion: false,
    KO: 7,
    DES: 9,
    SUB: 1,
    img: "/IanMachadoGary.webp",
    age: 28,
    height: 191,
    weight: 77.1,
    debut: "06.11.21",
    armSpan: 189,
  },
  {
    name: "Carlos Prates",
    nickname: "The Nightmare",
    rang: 2,
    victory: 24,
    defeat: 7,
    draw: 0,
    country: "BR",
    isChampion: false,
    KO: 19,
    DES: 2,
    SUB: 3,
    img: "/CarlosPrates.webp",
    age: 32,
    height: 185,
    weight: 77.1,
    debut: "10.02.24",
    armSpan: 198,
  },
  {
    name: "Michael Morales",
    nickname: null,
    rang: 3,
    victory: 19,
    defeat: 0,
    draw: 0,
    country: "EC",
    isChampion: false,
    KO: 14,
    DES: 4,
    SUB: 1,
    img: "/MichaelMorales.webp",
    age: 26,
    height: 183,
    weight: 77.1,
    debut: "22.01.22",
    armSpan: 201,
  },
  {
    name: "Jack Della Maddalena",
    nickname: "JDM",
    rang: 4,
    victory: 18,
    defeat: 4,
    draw: 0,
    country: "AU",
    isChampion: false,
    KO: 12,
    DES: 4,
    SUB: 2,
    img: "/JackDellaMaddalena.webp",
    age: 29,
    height: 180,
    weight: 77.1,
    debut: "22.01.22",
    armSpan: 185,
  },
  {
    name: "Belal Muhammad",
    nickname: "Remember The Name",
    rang: 5,
    victory: 24,
    defeat: 5,
    draw: 0,
    country: "US",
    isChampion: false,
    KO: 5,
    DES: 18,
    SUB: 1,
    img: "/BelalMuhammad.webp",
    age: 37,
    height: 180,
    weight: 77.1,
    debut: "07.07.16",
    armSpan: 183,
  },
  {
    name: "Sean Brady",
    nickname: "The Quiet Storm",
    rang: 6,
    victory: 19,
    defeat: 2,
    draw: 0,
    country: "US",
    isChampion: false,
    KO: 3,
    DES: 10,
    SUB: 6,
    img: "/SeanBrady.webp",
    age: 33,
    height: 178,
    weight: 77.1,
    debut: "18.10.19",
    armSpan: 183,
  },
  {
    name: "Leon Edwards",
    nickname: "Rocky",
    rang: 7,
    victory: 22,
    defeat: 6,
    draw: 0,
    country: "JM",
    isChampion: false,
    KO: 7,
    DES: 12,
    SUB: 3,
    img: "/LeonEdwards.webp",
    age: 34,
    height: 183,
    weight: 77.1,
    debut: "09.11.14",
    armSpan: 188,
  },
  {
    name: "Kamaru Usman",
    nickname: "Nigerian Nightmare",
    rang: 8,
    victory: 21,
    defeat: 4,
    draw: 0,
    country: "NG",
    isChampion: false,
    KO: 9,
    DES: 11,
    SUB: 1,
    img: "/KamaruUsman.webp",
    age: 38,
    height: 183,
    weight: 77.1,
    debut: "12.07.15",
    armSpan: 193,
  },
  {
    name: "Joaquin Buckley",
    nickname: "New Mansa",
    rang: 9,
    victory: 21,
    defeat: 8,
    draw: 0,
    country: "US",
    isChampion: false,
    KO: 15,
    DES: 6,
    SUB: 0,
    img: "/JoaquinBuckley.webp",
    age: 32,
    height: 178,
    weight: 77.1,
    debut: "08.08.20",
    armSpan: 193,
  },
  {
    name: "Gabriel Bonfim",
    nickname: "Marretinha",
    rang: 10,
    victory: 19,
    defeat: 1,
    draw: 0,
    country: "BR",
    isChampion: false,
    KO: 4,
    DES: 2,
    SUB: 13,
    img: "/GabrielBonfim.webp",
    age: 28,
    height: 185,
    weight: 77.1,
    debut: "21.01.23",
    armSpan: 184,
  },
  {
    name: "Mike Malott",
    nickname: "Proper",
    rang: 11,
    victory: 14,
    defeat: 2,
    draw: 1,
    country: "CA",
    isChampion: false,
    KO: 6,
    DES: 2,
    SUB: 6,
    img: "/MikeMalott.webp",
    age: 34,
    height: 185,
    weight: 77.1,
    debut: "09.04.22",
    armSpan: 185,
  },
  {
    name: "Uros Medic",
    nickname: "The Doctor",
    rang: 12,
    victory: 13,
    defeat: 3,
    draw: 0,
    country: "RS",
    isChampion: false,
    KO: 11,
    DES: 0,
    SUB: 2,
    img: "/UrosMedich.webp",
    age: 33,
    height: 185,
    weight: 77.1,
    debut: "06.03.21",
    armSpan: 180,
  },
  {
    name: "Michael Page",
    nickname: "Venom",
    rang: 13,
    victory: 25,
    defeat: 3,
    draw: 0,
    country: "GB",
    isChampion: false,
    KO: 13,
    DES: 9,
    SUB: 3,
    img: "/MichaelPage.webp",
    age: 39,
    height: 191,
    weight: 77.1,
    debut: "09.03.24",
    armSpan: 201,
  },
  {
    name: "Yaroslav Amosov",
    nickname: "Dynamo",
    rang: 14,
    victory: 29,
    defeat: 1,
    draw: 0,
    country: "UA",
    isChampion: false,
    KO: 9,
    DES: 8,
    SUB: 12,
    img: "/YaroslavAmosov.webp",
    age: 32,
    height: 183,
    weight: 77.1,
    debut: "13.12.25",
    armSpan: 191,
  },
  {
    name: "Daniel Rodriguez",
    nickname: "D-Rod",
    rang: 15,
    victory: 20,
    defeat: 5,
    draw: 0,
    country: "US",
    isChampion: false,
    KO: 9,
    DES: 7,
    SUB: 4,
    img: "/DanielRodriguez.webp",
    age: 38,
    height: 185,
    weight: 77.1,
    debut: "15.02.20",
    armSpan: 188,
  },
];