import type { UfcWeightClass } from "../../../constants/weights";

export type FightEntry = {
  fighter1: string;
  fighter2: string;
  weightClass: string;
  result?: string;
  method?: string;
  isMain?: boolean;
  isTitle?: boolean;
};

export type TournamentType = {
  dateDay: string;
  dateMonth: string;
  place: string;
  name: string;
  weight: UfcWeightClass;
  type: "NUMBERED" | "FIGHT NIGHT" | "PAST" | "FREEDOM";
  mainResult: string;
  fights: FightEntry[];
};

const pastTournaments: TournamentType[] = [
  {
    dateDay: "24",
    dateMonth: "Jan",
    place: "USA",
    type: "PAST",
    name: "UFC 324: Gaethje vs Pimblett",
    weight: "Lightweight",
    mainResult: "Gaethje def. Pimblett — UD",
    fights: [
      {
        fighter1: "Justin Gaethje",
        fighter2: "Paddy Pimblett",
        weightClass: "lightweight",
        result: "Gaethje",
        method: "UD (R5)",
        isMain: true,
      },
    ],
  },
  {
    dateDay: "31",
    dateMonth: "Jan",
    place: "Australia",
    type: "PAST",
    name: "UFC 325: Volkanovski vs Lopes 2",
    weight: "Featherweight",
    mainResult: "Volkanovski def. Lopes — UD",
    fights: [
      {
        fighter1: "Alexander Volkanovski",
        fighter2: "Diego Lopes",
        weightClass: "featherweight",
        result: "Volkanovski",
        method: "UD (R5)",
        isMain: true,
      },
    ],
  },
  {
    dateDay: "7",
    dateMonth: "Feb",
    place: "USA",
    type: "PAST",
    name: "UFC Fight Night 266: Bautista vs Oliveira",
    weight: "Bantamweight",
    mainResult: "Bautista def. Oliveira — SUB R2",
    fights: [
      {
        fighter1: "Mario Bautista",
        fighter2: "Vinicius Oliveira",
        weightClass: "bantamweight",
        result: "Bautista",
        method: "SUB R2",
        isMain: true,
      },
    ],
  },
  {
    dateDay: "21",
    dateMonth: "Feb",
    place: "USA",
    type: "PAST",
    name: "UFC Fight Night 267: Strickland vs Hernandez",
    weight: "Middleweight",
    mainResult: "Strickland def. Hernandez — TKO R3",
    fights: [
      {
        fighter1: "Sean Strickland",
        fighter2: "Anthony Hernandez",
        weightClass: "middleweight",
        result: "Strickland",
        method: "TKO R3",
        isMain: true,
      },
    ],
  },
  {
    dateDay: "28",
    dateMonth: "Feb",
    place: "Mexico",
    type: "PAST",
    name: "UFC Fight Night 268: Moreno vs Kavanagh",
    weight: "Flyweight",
    mainResult: "Moreno def. Kavanagh — UD",
    fights: [
      {
        fighter1: "Brandon Moreno",
        fighter2: "Lone'er Kavanagh",
        weightClass: "flyweight",
        result: "Moreno",
        method: "UD (R3)",
        isMain: true,
      },
    ],
  },
  {
    dateDay: "7",
    dateMonth: "Mar",
    place: "USA",
    type: "PAST",
    name: "UFC 326: Holloway vs Oliveira 2",
    weight: "Lightweight",
    mainResult: "Holloway def. Oliveira — UD",
    fights: [
      {
        fighter1: "Max Holloway",
        fighter2: "Charles Oliveira",
        weightClass: "lightweight",
        result: "Holloway",
        method: "UD (R5)",
        isMain: true,
      },
    ],
  },
  {
    dateDay: "14",
    dateMonth: "Mar",
    place: "USA",
    type: "PAST",
    name: "UFC Fight Night 269: Emmett vs Vallejos",
    weight: "Featherweight",
    mainResult: "Emmett def. Vallejos — TKO R1",
    fights: [
      {
        fighter1: "Josh Emmett",
        fighter2: "Kevin Vallejos",
        weightClass: "featherweight",
        result: "Emmett",
        method: "TKO R1",
        isMain: true,
      },
    ],
  },
  {
    dateDay: "21",
    dateMonth: "Mar",
    place: "United Kingdom",
    type: "PAST",
    name: "UFC Fight Night 270: Evloev vs Murphy",
    weight: "Featherweight",
    mainResult: "Evloev def. Murphy — MD",
    fights: [
      {
        fighter1: "Movsar Evloev",
        fighter2: "Lerone Murphy",
        weightClass: "featherweight",
        result: "Evloev",
        method: "MD (R3)",
        isMain: true,
      },
    ],
  },
  {
    dateDay: "28",
    dateMonth: "Mar",
    place: "USA, Seattle",
    type: "PAST",
    name: "UFC Fight Night 271: Adesanya vs Pyfer",
    weight: "Middleweight",
    mainResult: "Adesanya def. Pyfer",
    fights: [
      {
        fighter1: "Israel Adesanya",
        fighter2: "Joe Pyfer",
        weightClass: "middleweight",
        result: "Adesanya",
        method: "UD",
        isMain: true,
      },
      {
        fighter1: "Alexa Grasso",
        fighter2: "Maycee Barber",
        weightClass: "flyweightWomen",
        result: "Grasso",
        method: "UD",
      },
    ],
  },
  {
    dateDay: "4",
    dateMonth: "Apr",
    place: "USA, Las Vegas",
    type: "PAST",
    name: "UFC Fight Night 272: Moicano vs Duncan",
    weight: "Lightweight",
    mainResult: "Moicano def. Duncan",
    fights: [
      {
        fighter1: "Renato Moicano",
        fighter2: "Chris Duncan",
        weightClass: "lightweight",
        result: "Moicano",
        method: "UD",
        isMain: true,
      },
      {
        fighter1: "Virna Jandiroba",
        fighter2: "Tabatha Ricci",
        weightClass: "strawweightWomen",
        result: "Jandiroba",
        method: "UD",
      },
    ],
  },
  {
    dateDay: "11",
    dateMonth: "Apr",
    place: "USA, Miami",
    type: "PAST",
    name: "UFC 327: Prochazka vs Ulberg",
    weight: "LightHeavyweight",
    mainResult: "Prochazka def. Ulberg",
    fights: [
      {
        fighter1: "Jiri Prochazka",
        fighter2: "Carlos Ulberg",
        weightClass: "lightHeavyWeight",
        result: "Prochazka",
        method: "TKO R3",
        isMain: true,
      },
      {
        fighter1: "Joshua Van",
        fighter2: "Tatsuro Taira",
        weightClass: "flyweight",
        result: "Canceled (Van injury)",
        method: "—",
      },
    ],
  },
  {
    dateDay: "18",
    dateMonth: "Apr",
    place: "Canada, Winnipeg",
    type: "PAST",
    name: "UFC Fight Night 273: Burns vs Malott",
    weight: "Welterweight",
    mainResult: "Burns def. Malott",
    fights: [
      {
        fighter1: "Gilbert Burns",
        fighter2: "Mike Malott",
        weightClass: "welterweight",
        result: "Burns",
        method: "SUB R2",
        isMain: true,
      },
      {
        fighter1: "Kyler Phillips",
        fighter2: "Charles Jourdain",
        weightClass: "featherweight",
        result: "Jourdain",
        method: "TKO R2",
      },
    ],
  },
  {
    dateDay: "25",
    dateMonth: "Apr",
    place: "USA, Las Vegas",
    type: "PAST",
    name: "UFC Fight Night 274: Sterling vs Zalal",
    weight: "Featherweight",
    mainResult: "Sterling def. Zalal",
    fights: [
      {
        fighter1: "Aljamain Sterling",
        fighter2: "Youssef Zalal",
        weightClass: "featherweight",
        result: "Sterling",
        method: "UD",
        isMain: true,
      },
    ],
  },
  {
    dateDay: "2",
    dateMonth: "May",
    place: "Australia, Perth",
    type: "PAST",
    name: "UFC Fight Night 275: Della Maddalena vs Prates",
    weight: "Welterweight",
    mainResult: "Della Maddalena def. Prates",
    fights: [
      {
        fighter1: "Jack Della Maddalena",
        fighter2: "Carlos Prates",
        weightClass: "welterweight",
        result: "Della Maddalena",
        method: "KO R1",
        isMain: true,
      },
      {
        fighter1: "Beneil Dariush",
        fighter2: "Quillan Salkilld",
        weightClass: "lightweight",
        result: "Dariush",
        method: "SUB R1",
      },
    ],
  },
  {
    dateDay: "9",
    dateMonth: "May",
    place: "USA, Newark",
    type: "PAST",
    name: "UFC 328: Chimaev vs Strickland",
    weight: "Middleweight",
    mainResult: "Strickland def. Chimaev — SD (new champion!)",
    fights: [
      {
        fighter1: "Sean Strickland",
        fighter2: "Khamzat Chimaev (c)",
        weightClass: "middleweight",
        result: "Strickland",
        method: "SD (47–48, 48–47, 48–47)",
        isMain: true,
        isTitle: true,
      },
      {
        fighter1: "Joshua Van (c)",
        fighter2: "Tatsuro Taira",
        weightClass: "flyweight",
        result: "Van",
        method: "TKO R5 (1:32)",
        isTitle: true,
      },
      {
        fighter1: "Alexander Volkov",
        fighter2: "Waldo Cortes-Acosta",
        weightClass: "heavyweight",
        result: "Volkov",
        method: "UD (30–27, 29–28, 29–28)",
      },
      {
        fighter1: "Sean Brady",
        fighter2: "Joaquin Buckley",
        weightClass: "welterweight",
        result: "Brady",
        method: "UD (30–25, 30–25, 30–27)",
      },
      {
        fighter1: "King Green",
        fighter2: "Jeremy Stephens",
        weightClass: "lightweight",
        result: "Green",
        method: "SUB R1 (4:20)",
      },
      {
        fighter1: "Yaroslav Amosov",
        fighter2: "Joel Alvarez",
        weightClass: "welterweight",
        result: "Amosov",
        method: "SUB R2 (1:13)",
      },
      {
        fighter1: "Grant Dawson",
        fighter2: "Mateusz Rebecki",
        weightClass: "lightweight",
        result: "Dawson",
        method: "SUB R3 (4:42)",
      },
      {
        fighter1: "Jim Miller",
        fighter2: "Jared Gordon",
        weightClass: "lightweight",
        result: "Miller",
        method: "SUB R1 (3:29)",
      },
    ],
  },
  {
    dateDay: "16",
    dateMonth: "May",
    place: "USA, Las Vegas",
    type: "PAST",
    name: "UFC Fight Night 276: Allen vs Costa",
    weight: "Featherweight",
    mainResult: "Allen def. Costa — UD (50–45, 50–45, 49–46)",
    fights: [
      {
        fighter1: "Arnold Allen",
        fighter2: "Melquizael Costa",
        weightClass: "featherweight",
        result: "Allen",
        method: "UD (50–45, 50–45, 49–46)",
        isMain: true,
      },
      {
        fighter1: "Doo Ho Choi",
        fighter2: "Daniel Santos",
        weightClass: "featherweight",
        result: "Choi",
        method: "TKO R2 (4:29)",
      },
      {
        fighter1: "Juan Diaz",
        fighter2: "Malcolm Wellmaker",
        weightClass: "lightweight",
        result: "Diaz",
        method: "SUB R2 (4:08)",
      },
      {
        fighter1: "Modestas Bukauskas",
        fighter2: "Chrisitan Edwards",
        weightClass: "lightHeavyWeight",
        result: "Bukauskas",
        method: "SD",
      },
      {
        fighter1: "Bernardo Sopaj",
        fighter2: "Timothy Cuamba",
        weightClass: "flyweight",
        result: "Sopaj",
        method: "SUB R2",
      },
      {
        fighter1: "Chaos Williams",
        fighter2: "Nikolay Veretennikov",
        weightClass: "lightHeavyWeight",
        result: "Williams",
        method: "TKO R1",
      },
      {
        fighter1: "Thomas Gant",
        fighter2: "Artur Minev",
        weightClass: "heavyweight",
        result: "Gant",
        method: "TKO R2",
      },
      {
        fighter1: "Ketlen Vieira",
        fighter2: "Jacqueline Cavalcanti",
        weightClass: "bantamweightWomen",
        result: "Vieira",
        method: "UD",
      },
    ],
  },
];

const futureTournaments: TournamentType[] = [
  {
    dateDay: "30",
    dateMonth: "May",
    place: "China, Macau",
    type: "FIGHT NIGHT",
    name: "UFC Fight Night 277: Song Yadong vs Figueiredo",
    weight: "Bantamweight",
    mainResult: "Fights announced",
    fights: [
      { fighter1: "Song Yadong", fighter2: "Deiveson Figueiredo", weightClass: "bantamweight", isMain: true },
      { fighter1: "Zhang Mingyang", fighter2: "Alonzo Menifield", weightClass: "lightHeavyWeight" },
      { fighter1: "Sergei Pavlovich", fighter2: "Tallison Teixeira", weightClass: "heavyweight" },
      { fighter1: "Kai Asakura", fighter2: "Cameron Smotherman", weightClass: "bantamweight" },
      { fighter1: "Muslim Salikhov", fighter2: "Jake Matthews", weightClass: "welterweight" },
      { fighter1: "Alex Perez", fighter2: "Su Mudaerji", weightClass: "flyweight" },
      { fighter1: "Angela Hill", fighter2: "Xiong Jingnan", weightClass: "strawweightWomen" },
    ],
  },
  {
    dateDay: "6",
    dateMonth: "Jun",
    place: "USA, Las Vegas",
    type: "FIGHT NIGHT",
    name: "UFC Fight Night 278: Muhammad vs Bonfim",
    weight: "Welterweight",
    mainResult: "Fights announced",
    fights: [
      { fighter1: "Belal Muhammad", fighter2: "Gabriel Bonfim", weightClass: "welterweight", isMain: true },
      { fighter1: "Jordan Leavitt", fighter2: "Joanderson Brito", weightClass: "featherweight" },
    ],
  },
  {
    dateDay: "14",
    dateMonth: "Jun",
    place: "USA, Washington",
    type: "FREEDOM",
    name: "UFC Freedom 250: Topuria vs Gaethje",
    weight: "Lightweight",
    mainResult: "Main card announced",
    fights: [
      { fighter1: "Ilia Topuria (17-0)", fighter2: "Justin Gaethje (27-5)", weightClass: "lightweight", isMain: true, isTitle: true },
      { fighter1: "Alex Pereira (13-3)", fighter2: "Ciryl Gane (13-2)", weightClass: "heavyweight", isTitle: true },
      { fighter1: "Sean O'Malley (19-3)", fighter2: "Aiemann Zahabi (14-2)", weightClass: "bantamweight" },
      { fighter1: "Mauricio Ruffy (13-2)", fighter2: "Michael Chandler (23-10)", weightClass: "lightweight" },
      { fighter1: "Bo Nickal (8-1)", fighter2: "Kyle Daukaus (17-4)", weightClass: "middleweight" },
      { fighter1: "Diego Lopes (27-8)", fighter2: "Steve Garcia (19-5)", weightClass: "featherweight" },
    ],
  },
  {
    dateDay: "21",
    dateMonth: "Jun",
    place: "USA, Las Vegas",
    type: "FIGHT NIGHT",
    name: "UFC Fight Night: Kape vs Horiguchi",
    weight: "Flyweight",
    mainResult: "Details pending",
    fights: [
      { fighter1: "Brandon Moreno", fighter2: "Dante Leon", weightClass: "welterweight", isMain: true },
    ],
  },
  {
    dateDay: "27",
    dateMonth: "Jun",
    place: "Baku, Azerbaijan",
    type: "FIGHT NIGHT",
    name: "UFC Fight Night: Fiziev vs Torres",
    weight: "Lightweight",
    mainResult: "Details pending",
    fights: [
      { fighter1: "Rafael Fiziev", fighter2: "Rene Torres", weightClass: "lightweight", isMain: true },
    ],
  },
];

export { futureTournaments, pastTournaments };